import "MaterialIcons.ttf"; 

// An material icon font component.
export MaterialIcon := Rectangle {
    property<brush> icon_color: #ffffff;
    property<string> icon <=> i_icon.text;
    property<length> icon_size: 0px;

    width: icon != "" ? icon_size : 0px;
    height: icon != "" ? icon_size : 0px;

    i_icon := Text {
        font_family: "Material Icons";
        x: (parent.width - width) / 2;
        y: (parent.height - height) / 2;
        font_size <=> root.icon_size;
        color <=> root.icon_color;
    }
}