// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

// `CenterLayout` aligns its child vertical and horizontal center.
export CenterLayout := VerticalLayout {
    alignment: center;

    HorizontalLayout {  
        alignment: center;

        @children
    }
}

// Example for the viewer.
Example := Rectangle {
    width: 400px;
    height: 400px;
    background: red;

    CenterLayout {  
        Rectangle {  
            min_width: 100px;
            min_height: 100px;
            background: blue;
        }
    }
}