import { VerticalSeparator, HorizontalSeparator } from "separator.slint";
import { Spacer, VerticalSpacerSmall, VerticalSpacerMedium, VerticalSpacerLarge, HorizontalSpacerSmall, HorizontalSpacerMedium, HorizontalSpacerLarge  } from "spacer.slint";

export { VerticalSeparator, HorizontalSeparator }
export { Spacer, VerticalSpacerSmall, VerticalSpacerMedium, VerticalSpacerLarge, HorizontalSpacerSmall, HorizontalSpacerMedium, HorizontalSpacerLarge  }