// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";

// Fills the remaining spae in a layout.
export Spacer := Rectangle {}

// Fills vertical space with `co.spaces.small`.
export VerticalSpacerSmall := Spacer {
    height: co.spaces.small;
}

// Fills vertical space with `co.spaces.medium`.
export VerticalSpacerMedium := Spacer {
    height: co.spaces.medium;
}

// Fills vertical space with `co.spaces.large`.
export VerticalSpacerLarge := Spacer {
    height: co.spaces.large;
}

// Fills horizontal space with `co.spaces.small`.
export HorizontalSpacerSmall := Spacer {
    width: co.spaces.small;
}

// Fills horizontal space with `co.spaces.medium`.
export HorizontalSpacerMedium := Spacer {
    width: co.spaces.medium;
}

// Fills horizontal space with `co.spaces.large`.
export HorizontalSpacerLarge := Spacer {
    width: co.spaces.large;
}