// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Page } from "page.slint";
import { RowTitle, ColumnTitle } from "titles.slint";

import { Button, OutlineButton, RoundButton, RoundOutlineButton, Spacer, HorizontalSeparator,
    VerticalSpacerMedium, TextLine, CheckBox, Switch, Slider, ProgressBar, mi, co } from "../_imports/co_widgets.slint";

import { AppManager } from "../app_manager.slint";

export BasicsPage := Page {
    title: "Basics";

    GridLayout {  
        padding: co.theme.spaces.large;
        spacing: co.theme.spaces.medium;
       
        // Button
        Row {
            RowTitle {
                text: "Button";
            }
        }

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text+Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Primary";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            HorizontalLayout {  
                alignment: start;

                Button {
                    text: "Button";
                    enabled: AppManager.widgets_enabled;
                }
            }
          
            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    icon: mi.plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    text: "Button";
                    icon: mi.plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    primary: true;
                    text: "Primary";
                    enabled: AppManager.widgets_enabled;
                }
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // OutlineButton
        Row {
            RowTitle {
                text: "OutlineButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text+Icon";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            HorizontalLayout {  
                alignment: start;

                OutlineButton {
                    text: "OutlineButton";
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;
                
                OutlineButton {
                    icon: mi.plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {} 

            HorizontalLayout {  
                alignment: start;

                OutlineButton {
                    text: "OutlineButton";
                    icon: mi.plus;
                    enabled: AppManager.widgets_enabled;
                }
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // RoundButton
        Row {
            RowTitle {
                text: "RoundButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            RoundButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundButton {
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // RoundOutlineButton
        Row {
            RowTitle {
                text: "RoundOutlineButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}
            Spacer {}
            Spacer {}

            ColumnTitle {  
                text: "Primary";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            RoundOutlineButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundOutlineButton {
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}
            Spacer {}
            Spacer {}

            RoundOutlineButton {
                primary: true;
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // TextLine
        Row {
            RowTitle {
                text: "TextLine";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Empty";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon+HasClear";
            }

            Spacer {}

            ColumnTitle {  
                text: "Password";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            TextLine {
                text <=> AppManager.text_line_one;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;

                clicked => { root.open_keyboard("text_line_one", text, placeholder, icon); }
            }

            Spacer {}

            TextLine {
                icon: mi.search;
                text <=> AppManager.text_line_two;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;

                clicked => { root.open_keyboard("text_line_two", text, placeholder, icon); }
            }

            Spacer {}

            TextLine {
                text <=> AppManager.text_line_three;
                icon: mi.search;
                has-clear: true;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;

                clicked => { root.open_keyboard("text_line_three", text, placeholder, icon); }
            }

            Spacer {}

            TextLine {  
                placeholder: "Insert a password";
                input_type: password;
                text: "password";
            }
        }

        Row {
            VerticalSpacerMedium {}
        } 

        // Switch
        Row {
            RowTitle {
                text: "Switch";
            }
        }  

        Row {
            ColumnTitle {  
                text: "No Icons";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icons";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            Switch {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            Switch {  
                on_icon: mi.check;
                off_icon: mi.close;
                enabled: AppManager.widgets_enabled;
                selected: true;
            }
        }

        Row {
            VerticalSpacerMedium {}
        } 

        // CheckBox
        Row {
            RowTitle {
                text: "CheckBox";
            }
        }  

        Row {
            ColumnTitle {  
                text: "No Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            CheckBox {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            CheckBox {  
                text: "CheckBox";
                enabled: AppManager.widgets_enabled;
                selected: true;
            }
        }

        // Slider
        Row {
            RowTitle {
                text: "Slider";
            }
        }  

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            slider := Slider {
                colspan: 2;
                value: 0.5;
                enabled: AppManager.widgets_enabled;
            }
        }

        // ProgressBar
        Row {
            RowTitle {
                text: "ProgressBar";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Progress";
            }

            Spacer {}
           

            ColumnTitle {  
                text: "Indeterminate";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            ProgressBar {
                colspan: 2;
                progress: slider.value;
            }

            Spacer {}

            ProgressBar {
                // colspan: 2;
                indeterminate: true;
            }

            Spacer {}
        }

        // Fills the remaining available space
        Row {
            Spacer {}
        }
    }
}