// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Page } from "page.slint";
import { RowTitle, ColumnTitle } from "titles.slint";

import { Button, OutlineButton, RoundButton, RoundOutlineButton, ComboBox, Spacer, HorizontalSeparator, ComboBox,
    VerticalSpacerMedium, TextLine, CheckBox, Switch, Slider, ProgressBar, Popup, SmallLabel, Theme, Icons } from "../_imports/coop_widgets.slint";

import { AppManager } from "../app_manager.slint";

export component BasicsPage inherits Page {
    title: "Basics";

    GridLayout {  
        padding: Theme.spaces.large;
        spacing: Theme.spaces.medium;
    
        // Button
        Row {
            RowTitle {
                text: "Button";
            }
        }

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text+Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Primary";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            HorizontalLayout {  
                alignment: start;

                Button {
                    text: "Button";
                    enabled: AppManager.widgets_enabled;
                }
            }
          
            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    icon: Icons.fa_var_plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    text: "Button";
                    icon: Icons.fa_var_plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;

                Button {
                    primary: true;
                    text: "Primary";
                    enabled: AppManager.widgets_enabled;
                }
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // OutlineButton
        Row {
            RowTitle {
                text: "OutlineButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text+Icon";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            HorizontalLayout {  
                alignment: start;

                OutlineButton {
                    text: "OutlineButton";
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {}

            HorizontalLayout {  
                alignment: start;
                
                OutlineButton {
                    icon: Icons.fa_var_plus;
                    enabled: AppManager.widgets_enabled;
                }
            }

            Spacer {} 

            HorizontalLayout {  
                alignment: start;

                OutlineButton {
                    text: "OutlineButton";
                    icon: Icons.fa_var_plus;
                    enabled: AppManager.widgets_enabled;
                }
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // RoundButton
        Row {
            RowTitle {
                text: "RoundButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            RoundButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundButton {
                icon: Icons.fa_var_plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // RoundOutlineButton
        Row {
            RowTitle {
                text: "RoundOutlineButton";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon";
            }

            Spacer {}
            Spacer {}
            Spacer {}

            ColumnTitle {  
                text: "Primary";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            RoundOutlineButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundOutlineButton {
                icon: Icons.fa_var_plus;
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}
            Spacer {}
            Spacer {}

            RoundOutlineButton {
                primary: true;
                icon: Icons.fa_var_plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // TextLine
        Row {
            RowTitle {
                text: "TextLine";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Empty";
            }

            Spacer {}

            ColumnTitle {  
                text: "Error (insert float to remove)";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icon + Action Icon";
            }

            Spacer {}

            ColumnTitle {  
                text: "Password";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            TextLine {
                text <=> AppManager.text_line_one;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;

                clicked => { root.open_keyboard("text_line_one", self.text, self.placeholder, self.icon); }
            }

            Spacer {}

            TextLine { 
                text <=> AppManager.text_line-two;
                icon: Icons.fa_var_list;
                action_icon: Icons.fa_var_remove;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;
                placeholder: "Insert a float";
                has_error: !self.text.is_float();

                action => { self.text = "" }
                clicked => { root.open_keyboard("text_line", self.text, self.placeholder, self.icon); }
            }

            Spacer {}

            TextLine {
                text <=> AppManager.text_line_three;
                icon: Icons.fa_var_search;
                action_icon: Icons.fa_var_remove;
                enabled: AppManager.widgets_enabled;
                clickable: AppManager.keyboard_enabled;

                action => { self.text = "" }
                clicked => { root.open_keyboard("text_line_three", self.text, self.placeholder, self.icon); }
            }

            Spacer {}

            TextLine {  
                placeholder: "Insert a password";
                input_type: password;
                text: "password";
                action_icon: self.input_type == InputType.password ? Icons.fa_var_eye : Icons.fa_var_eye_slash;
                enabled: AppManager.widgets_enabled;
                action => { 
                    if(self.input_type == InputType.password) {
                        self.input_type = InputType.text
                    } else {
                        self.input_type = InputType.password;
                    }
                }
            }
        }

        Row {
            VerticalSpacerMedium {}
        } 

         // ComboBox
         Row {
            RowTitle {
                text: "ComboBox";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Pre selected";
            }

            Spacer {}

            ColumnTitle {  
                text: "Placeholder";
            }

            Spacer {}

            ColumnTitle {  
                text: "With icons";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            ComboBox {
                enabled: AppManager.widgets_enabled;
                current_index: 0;
                model: [
                    {
                        text: "Item one"
                    },
                    {
                        text: "Item three"
                    },
                    {
                        text: "Item four"
                    }
                ];
            }

            Spacer {}

            ComboBox {
                enabled: AppManager.widgets_enabled;
                placeholder: "Select an item";
                model: [
                    {
                        text: "Item one"
                    },
                    {
                        text: "Item three"
                    },
                    {
                        text: "Item four"
                    }
                ];
            }

            Spacer {}

            ComboBox {
                enabled: AppManager.widgets_enabled;
                current_index: 0;
                model: [
                    {
                        leading_icon: Icons.fa_var_wrench,
                        text: "Item one"
                    },
                    {
                        leading_icon: Icons.fa_var_print,
                        text: "Item three"
                    },
                    {
                        leading_icon: Icons.fa_var_calculator,
                        text: "Item four"
                    }
                ];
            }
        }

        Row {
            VerticalSpacerMedium {}
        } 

        // Switch
        Row {
            RowTitle {
                text: "Switch";
            }
        }  

        Row {
            ColumnTitle {  
                text: "No Icons";
            }

            Spacer {}

            ColumnTitle {  
                text: "Icons";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            Switch {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            Switch {  
                on_icon: Icons.fa_var_check;
                off_icon: Icons.fa_var_remove;
                enabled: AppManager.widgets_enabled;
                selected: true;
            }
        }

        Row {
            VerticalSpacerMedium {}
        } 

        // CheckBox
        Row {
            RowTitle {
                text: "CheckBox";
            }
        }  

        Row {
            ColumnTitle {  
                text: "No Text";
            }

            Spacer {}

            ColumnTitle {  
                text: "Text";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            CheckBox {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            CheckBox {  
                text: "CheckBox";
                enabled: AppManager.widgets_enabled;
                selected: true;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // Slider
        Row {
            RowTitle {
                text: "Slider";
            }
        }  

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            slider := Slider {
                colspan: 2;
                value: 0.5;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerMedium {}
        }

        // ProgressBar
        Row {
            RowTitle {
                text: "ProgressBar";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Progress";
            }

            Spacer {}
           

            ColumnTitle {  
                text: "Indeterminate";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            ProgressBar {
                colspan: 2;
                progress: slider.value;
            }

            Spacer {}

            ProgressBar {
                // colspan: 2;
                indeterminate: true;
            }

            Spacer {}
        }

        Row {
            VerticalSpacerMedium {}
        }

        // Popup
        Row {
            RowTitle {
                text: "Popup";
            }
        }  

        Row {
            ColumnTitle {  
                text: "Popup";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 8; 
            }
        }

        Row {
            HorizontalLayout { 
                alignment: start;

                i_popup_button := Button {
                    text: "Open popup";
                    clicked => { i_popup.show(); }
                }

                i_popup := Popup {
                    x: i_popup_button.x;
                    y: i_popup_button.y - 40px - Theme.spaces.small;
                    width: i_popup_button.width;
                    height: 40px;
                    
                    layout := VerticalLayout {  
                        padding: Theme.spaces.medium;
                        SmallLabel {
                            text: "Popup content";
                        }
                    }
                }
            }
        }

        // Fills the remaining available space
        Row {
            Spacer {}
        }
    }
}