// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { RowTitle, ColumnTitle } from "titles.slint";

import { Spacer, TableView, Cell, HorizontalSeparator, ScrollView, List, ListView, Theme, Icons, GroupItemModel, Switch, HeaderBar }
    from "../_imports/coop_widgets.slint";

export component ListPage inherits GridLayout {
    Row {
        i_header_bar := HeaderBar {
            title: "Lists";
            VerticalLayout {
                alignment: center;

                Switch {
                    on_icon: Icons.fa_var_lightbulb_o;
                    off_icon: Icons.fa_var_moon;
                    selected: !Theme.dark;
                    selected_changed(selected) => {
                        Theme.dark = !self.selected;
                    }
                }
            }
        }
    }

    Row {
        GridLayout {
            padding: Theme.spaces.large;
            spacing: Theme.spaces.medium;

            // Lists
            Row {
                RowTitle {
                    text: "Lists";
                }
            }

            Row {
                ColumnTitle {
                    text: "List (no scroll)";
                }

                Spacer {}

                ColumnTitle {
                    text: "ListView (scrolling)";
                }

                Spacer {}

                ColumnTitle {
                    text: "List with groups";
                }

                Spacer {}

                ColumnTitle {
                    text: "ScrollView";
                }
            }

            Row {
                HorizontalSeparator {
                    colspan: 8;
                }
            }

            Row {
                i_list := List {
                    property <GroupItemModel> list: {
                        items: [
                            { text: "Item 1" },
                            { text: "Item 2" },
                            { text: "Item 3" },
                            { text: "Item 4" },
                            { text: "Item 5" },
                            { text: "Item 6" },
                        ]
                    };
                    model: [self.list];
                }

                Spacer {}

                ListView {
                    height: 100px;
                    model: i_list.model;
                }

                Spacer {}

                List {
                    property <GroupItemModel> list_one: {
                        text: "Group 1",
                        items: [
                            { text: "Item 1", highlighted: true },
                            { text: "Item 2" },
                        ]
                    };
                    property <GroupItemModel> list_two: {
                        text: "Group 2",
                        items: [
                            { text: "Item 1" },
                            { text: "Item 2" },
                        ]
                    };
                    model: [self.list_one, self.list_two];
                }

                Spacer {}

                ScrollView {
                    height: 100px;

                    VerticalLayout {
                        spacing: 4px;

                        for i in [0, 1, 2, 3, 4, 5, 6, 7] : Rectangle {
                            height: 50px;
                            background: mod(i, 2) == 0 ? black : gray;
                        }
                    }
                }
            }

             // TableView
             Row {
                RowTitle {
                    text: "TableView";
                }
            }

            Row {
                HorizontalSeparator {
                    colspan: 8;
                }
            }

            Row {
                TableView {
                    colspan: 8;
                    private property <int> current_row: -1;

                    property <[Cell]> first_row: [
                        { value: Icons.fa_var_folder, type: 1, highlighted: true }, { value: "src" }, { value: "2022.11.10" }, { value: "--"}, { value: "Folder"}
                    ];

                    property <[Cell]> second_row: [
                        { value: Icons.fa_var_file, type: 1 }, { value: "test.slint"}, { value: "2022.11.10" }, { value: "17 KB" }, { value: "Document" }
                    ];

                    property <[Cell]> third_row: [
                        { value: Icons.fa_var_file, type: 1 }, { value: "test2.slint"}, { value: "2022.11.10" }, { value: "17 KB" }, { value: "Document" }
                    ];

                    accepted(row, cell, text) => {
                        self.rows[self.row][cell].editable = false;
                        self.rows[self.row][cell].value = text;
                        self.current_row = -1;
                    }

                    row_clicked(index) => {
                        if(self.current_row != -1) {
                            self.rows[self.current_row][1].editable = false;
                        }

                        self.current_row = index;
                        // column 1 is name
                        self.rows[index][1].editable = true;
                    }
                    columns: [
                        { min_width: 32px },
                        { header: "Name", horizontal_stretch: 2 },
                        { header: "Date Modified", horizontal_stretch: 1 },
                        { header: "Size", horizontal_stretch: 1 },
                        { header: "Kind", horizontal_stretch: 1 },
                    ];
                    rows: [
                        self.first_row,
                        self.second_row,
                        self.third_row
                    ];
                }
            }
        }
    }
}