// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { AppManager } from "../app_manager.slint"; 

import { HeaderBar, OutlineButton, CheckBox, Switch, ScrollView, Theme, Icons } from "../_imports/coop_widgets.slint";

export component Page inherits GridLayout {
    callback open_keyboard(string, string, string, string);
    in-out property <string> title <=> i_header_bar.title;
    in-out property <bool> keyboard_check_box: true;
    in-out property <bool> disabled_check_box: true;

    Row {
        i_header_bar := HeaderBar {
            if(root.keyboard_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Keyboard enabled";
                selected <=> AppManager.keyboard_enabled;
            }

            if(root.disabled_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Widgets enabled";
                selected <=> AppManager.widgets_enabled;
            }

            VerticalLayout {  
                alignment: center;

                Switch {
                    on_icon: Icons.fa_var_lightbulb_o;
                    off_icon: Icons.fa_var_moon;
                    selected: !Theme.dark;
                    selected_changed(selected) => {
                        Theme.dark = !self.selected;
                    }
                }
            }    
        }
    }

    Row {
        ScrollView {  
            @children
        }    
    }
}