// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { BasicsPage } from "basics_page.slint";
import { BookFlipPage } from "book_flip_page.slint";
import { BrushesPage } from "brushes_page.slint"; 
import { IconPage } from "icon_page.slint";
import { ListPage } from "list_page.slint";
import { TypoPage } from "typo_page.slint";

export { BasicsPage }
export { BookFlipPage }
export { BrushesPage }
export { IconPage }
export { TypoPage } 
export { ListPage } 