import { settings } from "../settings.slint"; 

import { HeaderBar, OutlineButton, CheckBox, Switch, co, mi } from "../_imports/co_widgets.slint";

export Page := GridLayout {
    property<string> title <=> i_header_bar.title;
  
    Row {
        i_header_bar := HeaderBar {
            CheckBox {
                y: (parent.height - height) / 2;
                text: "Keyboard enabled";
                selected <=> settings.keyboard_enabled;
            }

            CheckBox {
                y: (parent.height - height) / 2;
                text: "Widgets enabled";
                selected <=> settings.widgets_enabled;
            }

            Switch {
                y: (parent.height - height) / 2;
                on_icon: mi.lightbulb;
                off_icon: mi.nights_stay;
                selected: !co.dark_theme;
                selected_changed(selected) => {
                    co.dark_theme = !selected;
                }
            }
        }
    }

    Row {
        Flickable {  
            @children
        }    
    }
}