// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Page } from "page.slint";
import { RowTitle, ColumnTitle } from "titles.slint";

import {  SmallLabel, MediumLabel, LargeLabel, ErrorLabel, SmallTitle, MediumTitle, LargeTitle, Spacer, HorizontalSeparator,
    VerticalSpacerMedium, TextLine, CheckBox, Switch, mi, coop } from "../_imports/coop_widgets.slint";

export TypoPage := Page {
    title: "Typography";
    keyboard_check_box: false;
    disabled_check_box: false;

    GridLayout {  
        padding: coop.theme.spaces.large;
        spacing: coop.theme.spaces.medium;
       
        // Labels
        Row {
            RowTitle {
                text: "Labels";
            }
        }

        Row {
            ColumnTitle {  
                text: "Component";
            }

            Spacer {}

            ColumnTitle {  
                text: "key";
            }

            Spacer {}

            // ColumnTitle {  
            //     text: "font_family";
            // }

            // Spacer {}

            ColumnTitle {  
                text: "font_size";
            }

            Spacer {}

            ColumnTitle {  
                text: "font_weight";
            }
        }

        Row {
            HorizontalSeparator {
                colspan: 9; 
            }
        }

        // SmallLabel
        Row {
            SmallLabel {  
                text: "SmallLabel";
            }

            Spacer {}

            SmallLabel {  
                text: "coop.theme.typo.small_label";
            }

            Spacer {}

            // SmallLabel {  
            //     vertical-alignment: center;
            //     text: coop.theme.typo.small_label.family;
            // }

            // Spacer {}

            SmallLabel { 
                vertical-alignment: center; 
                text: "12px";
            }

            Spacer {}

            SmallLabel {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.small_label.weight}";
            }
        }

        // ErrorLabel
        Row {
            ErrorLabel {  
                text: "ErrorLabel";
            }

            Spacer {}

            ErrorLabel {  
                text: "coop.theme.typo.small_label";
            }

            Spacer {}

            // SmallLabel {  
            //     vertical-alignment: center;
            //     text: coop.theme.typo.small_label.family;
            // }

            // Spacer {}

            ErrorLabel { 
                vertical-alignment: center; 
                text: "12px";
            }

            Spacer {}

            ErrorLabel {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.small_label.weight}";
            }
        }

        // MediumLabel
        Row {
            MediumLabel {  
                text: "MediumLabel";
            }

            Spacer {}

            MediumLabel {  
                text: "coop.theme.typo.medium_label";
            }

            Spacer {}

            // MediumLabel { 
            //     vertical-alignment: center; 
            //     text: coop.theme.typo.medium_label.family;
            // }

            // Spacer {}

            MediumLabel {  
                vertical-alignment: center;
                text: "12px";
            }

            Spacer {}

            MediumLabel {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.medium_label.weight}";
            }
        }

        // LargeLabel
        Row {
            LargeLabel {  
                text: "LargeLabel";
            }

            Spacer {}

            LargeLabel {  
                vertical-alignment: center;
                text: "coop.theme.typo.large_label";
            }

            Spacer {}

            // LargeLabel {  
            //     vertical-alignment: center;
            //     text: coop.theme.typo.large_label.family;
            // }

            // Spacer {}

            LargeLabel {  
                text: "14px";
            }

            Spacer {}

            LargeLabel {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.large_label.weight}";
            }
        }

        // SmallTitle
        Row {
            SmallTitle {  
                text: "SmallTitle";
            }

            Spacer {}

            SmallTitle {  
                vertical-alignment: center;
                text: "coop.theme.typo.small_title";
            }

            Spacer {}

            // SmallTitle {  
            //     vertical-alignment: center;
            //     text: coop.theme.typo.small_title.family;
            // }

            // Spacer {}

            SmallTitle {  
                vertical-alignment: center;
                text: "16px";
            }

            Spacer {}

            SmallTitle {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.small_title.weight}";
            }
        }

        // MediumTitle
        Row {
            MediumTitle {  
                text: "MediumTitle";
            }

            Spacer {}

            MediumTitle {  
                vertical-alignment: center;
                text: "coop.theme.typo.medium_title";
            }

            Spacer {}

            // MediumTitle { 
            //     vertical-alignment: center; 
            //     text: coop.theme.typo.medium_title.family;
            // }

            // Spacer {}

            MediumTitle {  
                vertical-alignment: center;
                text: "20px";
            }

            Spacer {}

            MediumTitle {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.medium_title.weight}";
            }
        }

        // LargeTitle
        Row {
            LargeTitle {  
                text: "LargeTitle";
            }

            Spacer {}

            LargeTitle {  
                vertical-alignment: center;
                text: "coop.theme.typo.large_title";
            }

            Spacer {}

            // LargeTitle {  
            //     vertical-alignment: center;
            //     text: coop.theme.typo.large_title.family;
            // }

            // Spacer {}

            LargeTitle {  
                vertical-alignment: center;
                text: "24px";
            }

            Spacer {}

            LargeTitle {  
                vertical-alignment: center;
                text: "\{coop.theme.typo.large_title.weight}";
            }
        }

         // Fills the remaining available space
         Row {
            Spacer {}
        }
    }
}