// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";
import { TitleLarge } from "../components/components.slint";
import { Spacer } from "../layouts/layouts.slint";

// A header bar with a title and a content area.
export HeaderBar := HorizontalLayout {
    // Defines the title text of the header bar
    property <string> title <=> i_title.text;

    spacing: co.theme.spaces.medium;
    padding_left: co.theme.spaces.large;
    padding_right: co.theme.spaces.large;
    padding_top: co.theme.spaces.small;
    padding_bottom: co.theme.spaces.small;
    height: co.theme.sizes.large;

    i_title := TitleLarge {  
        text: "title";
        vertical-alignment: center;
        horizontal_alignment: left;
        horizontal_stretch: 1;
    }

    @children
}