import { co } from "../co/co.slint";
import { TitleLarge } from "../components/components.slint";
import { Spacer } from "../layouts/layouts.slint";

// A header bar with a title and a content area.
export HeaderBar := HorizontalLayout {
    // Defines the title text of the header bar
    property<string> title <=> i_title.text;

    spacing: co.spaces.medium;
    padding_left: co.spaces.large;
    padding_right: co.spaces.large;
    height: co.sizes.large;

    i_title := TitleLarge {  
        text: "title";
        vertical-alignment: center;
    }

    Spacer {}

    @children
}