// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";

// A vertical layout with background.
export SideBar := Rectangle {
    background: co.theme.brushes.background_alt;
    
    VerticalLayout {  
        padding_top: co.theme.spaces.medium;
        padding_bottom: co.theme.spaces.medium;
        spacing: co.theme.spaces.large;

        @children
    }
}