// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";

// A vertical layout with background.
export SideBar := Rectangle {
    background: co.brushes.surface;
    
    VerticalLayout {  
        padding_top: co.spaces.medium;
        padding_bottom: co.spaces.medium;
        spacing: co.spaces.large;

        @children
    }
}