// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Size, Space } from "../styling/styling.slint";
import { LargeTitle } from "../components/components.slint";
import { RoundButton } from "../widgets/widgets.slint";
import { Spacer } from "../layouts/layouts.slint";

export component HeaderBar inherits HorizontalLayout {
    callback action();

    in property <string> title;
    in property <image> action-icon;
    in property <string> action-text;
    in property <bool> action-enabled: false;

    spacing: Space.medium;
    padding-left: Space.medium;
    padding-right: Space.medium;
    padding-top: Space.small;
    padding-bottom: Space.small;
    height: Size.large;

    if (root.action-text != "" || (root.action-icon.width > 0 && root.action-icon.height  > 0)) : RoundButton {
        enabled: root.action-enabled;
        text: root.action-text;
        icon: root.action-icon;

        clicked => {
            root.action();
        }
    }

    LargeTitle {
        text: root.title;
        vertical-alignment: center;
        horizontal-alignment: left;
        horizontal-stretch: 1;
        overflow: elide;
    }

    @children
}