// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Size, Space } from "../styling/styling.slint";
import { LargeTitle } from "../components/components.slint";
import { RoundButton } from "../widgets/widgets.slint";
import { Spacer } from "../layouts/layouts.slint";

export component HeaderBar inherits HorizontalLayout {
    callback action <=> i-action-button.clicked;

    in property <string> title;
    in property <image> action-icon <=> i-action-button.icon;
    in property <string> action-text <=> i-action-button.text;
    in property <bool> action-enabled <=> i-action-button.enabled;

    spacing: Space.medium;
    padding-left: Space.medium;
    padding-right: Space.medium;
    padding-top: Space.small;
    padding-bottom: Space.small;
    height: Size.large;

    i-action-button := RoundButton {
        visible: self.enabled;
    }

    if (root.title != "") : LargeTitle {
        text: root.title;
        vertical-alignment: center;
        horizontal-alignment: left;
        horizontal-stretch: 1;
        overflow: elide;
    }

    @children
}