// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// Internal helper struct to manage the brushes of the  `co` theme.
export struct Brushes := {
    background: brush,
    foreground: brush,
    foreground_disabled: brush,
    surface: brush,
    surface_disabled: brush,
    on_surface: brush,
    primary: brush,
    on_primary: brush,
    border: brush,
    border_disabled: brush,
    state: brush,
}