// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

// Defines additional settings for the co theme.
export struct Settings := {
    // If set to `true` some widgets are adjusted in size and handling e.g. the keyboard buttons.
    //
    // This property minimizes sizes and also the behavior of some widgets. 
    // This should be used if there some issues on mcu platforms like the pico.
    minimize: bool,
} 