// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// Internal helper struct the font settings of a label of the  `co` theme.
export struct Font := {
    size: length,
    // family: string,
    weight: int,
}

// Internal helper struct to manage typography settings of the  `co` theme.
export struct Typo := {
    label_small: Font,
    label_medium: Font,
    label_large: Font,
    title_small: Font,
    title_medium: Font,
    title_large: Font,
}