// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CenterLayout, Button, TextLine, TitleLarge, co } from "_imports/co_widgets.slint";
import { OsController } from "os_controller.slint";

export Login := CenterLayout {
    callback login();

    Rectangle {  
        background: co.theme.brushes.background_alt;
        border_radius: co.theme.radius.medium;

        i_layout := VerticalLayout {  
            padding: co.theme.spaces.large;
            spacing: co.theme.spaces.large;

            TitleLarge {
                text: "Pico OS";
            }

            i_user_name := TextLine {  
                placeholder: "User";
                text: "user";
            }

            i_password := TextLine {  
                placeholder: "Password";
                text: "password";
            }

            Button {  
                text: "Login";
                primary: true;
                clicked => {  
                    OsController.login(i_user_name.text, i_password.text);
                }
            }
        }
    }
}