import  { Brushes } from "brushes.slint";
import  { Durations } from "durations.slint";
import  { Icons } from "icons.slint";
import  { Opacities } from "opacities.slint";
import  { Radius } from "radius.slint";
import  { Sizes } from "sizes.slint";
import  { Spaces } from "spaces.slint";
import  { Typo, Font } from "typo.slint";

import "../assets/fonts/Roboto-Regular.ttf";
import "../assets/fonts/Roboto-Medium.ttf";

// Access to the style resources of teh `co` theme (dark and light).
export global co := { 
    // Toggles between light and dark theme.
    property<bool> dark-theme: true;

    // Defines the accent (primary) colo.
    property<brush> accent_color: dark-theme ? #01fec5 : #1d9bf2;

    // Access the brushes definitions of the `co` theme.
    property<Brushes> brushes : {
        background: dark-theme ? #2d2d2d : #dfdfdf,
        foreground: dark-theme ? #dfdfdf : #2d2d2d,
        surface: dark-theme ? #505050 : #BDBDBD,
        on_surface: dark-theme ? #212121 : #dfdfdf,
        primary: accent-color,
        border: dark-theme ? #7e7e7e : #505050,
        state: #000000,
    };

    // Access the animation duration definitions of the `co` theme.
    property<Durations> durations : {
        slow: 500ms,
        fast: 200ms,
    };

     // Access the animation duration definitions of the `co` theme.
     property<Icons> icons : {
        size_small: 12px,
        size_medium: 14px,
        size_large: 16px,
    };

    // Access the opacitie definitions of the `co` theme.
    property<Opacities> opacities : {
        state_hover: 0.12,
        state_presseed: 0.32,
    };

    // Access the radius definitions of the `co` theme.
     property<Radius> radius : {
        small: 4px,
        medium: 8px,
        large: 16px,
    };

    // Access the size definitions of the `co` theme.
    property<Sizes> sizes: {
        medium: 32px,
        large: 40px,
    };

    // Access the space definitions of the `co` theme.
    property<Spaces> spaces: {
        small: 4px,
        medium: 8px,
        large: 16px,
    };

     // Access the space definitions of the  `co` theme.
     property<Typo> typo: {
        label_small: {
            family: "Roboto",
            size: 10px,
            weight: 500
            
        },
        label_medium: {
            family: "Roboto",
            size: 12px,
            weight: 500
            
        },
        label_large: {
            family: "Roboto",
            size: 14px,
            weight: 500
        },
    };
}