// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> add: @image-url("../assets/icons/add.svg");
    out property <image> arrow-back: @image-url("../assets/icons/arrow_back.svg");
    out property <image> arrow-downward: @image-url("../assets/icons/arrow_downward.svg");
    out property <image> arrow-drop-down: @image-url("../assets/icons/arrow_drop_down.svg");
    out property <image> arrow-forward: @image-url("../assets/icons/arrow_forward.svg");
    out property <image> arrow-upward: @image-url("../assets/icons/arrow_upward.svg");
    out property <image> arrow-right: @image-url("../assets/icons/arrow_right.svg");
    out property <image> book: @image-url("../assets/icons/book.svg");
    out property <image> brush: @image-url("../assets/icons/brush.svg");
    out property <image> calculate: @image-url("../assets/icons/calculate.svg");
    out property <image> check: @image-url("../assets/icons/check.svg");
    out property <image> clear: @image-url("../assets/icons/clear.svg");
    out property <image> computer: @image-url("../assets/icons/computer.svg");
    out property <image> description: @image-url("../assets/icons/description.svg");
    out property <image> folder: @image-url("../assets/icons/folder.svg");
    out property <image> format-size: @image-url("../assets/icons/format_size.svg");
    out property <image> home: @image-url("../assets/icons/home.svg");
    out property <image> image: @image-url("../assets/icons/image.svg");
    out property <image> insert-drive-file: @image-url("../assets/icons/insert_drive_file.svg");
    out property <image> keyboard-return: @image-url("../assets/icons/keyboard_return.svg");
    out property <image> light-mode: @image-url("../assets/icons/light_mode.svg");
    out property <image> list: @image-url("../assets/icons/list.svg");
    out property <image> mode-night: @image-url("../assets/icons/mode_night.svg");
    out property <image> more-vert: @image-url("../assets/icons/more_vert.svg");
    out property <image> pin: @image-url("../assets/icons/pin.svg");
    out property <image> reorder: @image-url("../assets/icons/reorder.svg");
    out property <image> search: @image-url("../assets/icons/search.svg");
    out property <image> videogame-asset: @image-url("../assets/icons/videogame_asset.svg");
    out property <image> visibility-off: @image-url("../assets/icons/visibility_off.svg");
    out property <image> visibility: @image-url("../assets/icons/visibility.svg");
    out property <image> menu: @image-url("../assets/icons/menu.svg");

    // filled
    out property <image> filled-audio-file: @image-url("../assets/icons/filled_audio_file.svg");
    out property <image> filled-av-timer: @image-url("../assets/icons/filled_av_timer.svg");
    out property <image> filled-calendar-month: @image-url("../assets/icons/filled_calendar_month.svg");
    out property <image> filled-description: @image-url("../assets/icons/filled_description.svg");
    out property <image> filled-folder: @image-url("../assets/icons/filled_folder.svg");
    out property <image> filled-image: @image-url("../assets/icons/filled_image.svg");
    out property <image> filled-insert-drive-file: @image-url("../assets/icons/filled_insert_drive_file.svg");
    out property <image> filled-settings: @image-url("../assets/icons/filled_settings.svg");
    out property <image> filled-video-file: @image-url("../assets/icons/filled_video_file.svg");
    out property <image> filled-videogame-asset: @image-url("../assets/icons/filled_videogame_asset.svg");

}