// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { StyleMetrics } from "std-widgets.slint";

export global Palette {
    in-out property<bool> dark-color-scheme: StyleMetrics.dark-color-scheme;

    out property <brush> background: dark-color-scheme ? #2d2d2d: #dfdfdf;
    out property <brush> background-alt: dark-color-scheme ? #414141: #cbcbcb;
    out property <brush> foreground: dark-color-scheme ? #dfdfdf: #2d2d2d;
    out property <brush> foreground-disabled: dark-color-scheme ? #7b7b7b: #a0a0a0;
    out property <brush> surface: dark-color-scheme ? #505050: #BDBDBD;
    out property <brush> surface-disabled: dark-color-scheme ? #3d3d3d: #d2d2d2;
    out property <brush> on-surface: dark-color-scheme ? #212121: #dfdfdf;
    out property <brush> primary: accent;
    out property <brush> on-primary: on-accent;
    out property <brush> border: dark-color-scheme ? #7e7e7e: #505050;
    out property <brush> border-disabled: dark-color-scheme ? #494949: #c5c5c5;
    out property <brush> state: #000000;
    out property <brush> shadow: #000000;
    out property <brush> error: #EF5350;
    in-out property <brush> accent: dark-color-scheme ? #01fec5: #1d9bf2;
    in-out property <brush> on-accent: dark-color-scheme ? #212121: #dfdfdf;
}