import { co } from "../co/co.slint";
import { StateLayer } from "../components/components.slint";

// A Button with a `clicked` callback.
export Button := Rectangle {
    // Callback to handle button click.
    callback clicked <=> state_layer.clicked;
    
    // Defines the text that is displayed on the button.
    property<string> text: "text";

    width: size_helper.width + 2 * co.spaces.large;
    height: co.sizes.medium;

    container := Rectangle {
        x: (parent.width - width) / 2;
        y: (parent.height - height) / 2;
        width: 100%;
        height: 100%;
        border-width: 1px;
        border-color: co.colors.border;
        border-radius: co.radius.large;

        animate width { duration: co.durations.fast; easing: ease_in_out; }
        animate height { duration: co.durations.fast; easing: ease_in_out; }
    }

    size_helper := Text {
        text: label.text;
        visible: false;
        font_size: co.typo.label_medium.size;
        font_weight: label.font_weight;
        font_family: label.font_family;
    }

    label := Text {
        x: (parent.width - width) / 2;
        y: (parent.height - height) / 2;
        color: co.colors.foreground;
        text <=> root.text;
        vertical-alignment: center;
        horizontal-alignment: center;
        font_size: co.typo.label_medium.size;

        animate font_size { duration: co.durations.fast; easing: ease_in_out; }
    }

    state_layer := StateLayer {  
        x: (parent.width - width) / 2;
        y: (parent.height - height) / 2;
        width: 100%;
        height: 100%;
        border_radius: co.radius.large;

        animate width { duration: co.durations.fast; easing: ease_in_out; }
        animate height { duration: co.durations.fast; easing: ease_in_out; }
    }

    states [
        pressed when state_layer.pressed : {
            container.width: 96%;
            container.height: 96%;
            state_layer.width: 96%;
            state_layer.height: 96%;
            label.font_size: co.typo.label_medium.size - 1px;
        }
    ]
}