import { co } from "../co/co.slint";
import { StateLayer } from "../components/components.slint";
import { MaterialIcon } from "../assets/icons/material_icon.slint";

export TextLine := Rectangle {
    property<string> icon <=> i_icon.icon;
    property<string> placeholder: "placeholder";


    min_width: 168px;
    height: co.sizes.medium;

    i_container := Rectangle {
        width: 100%;
        height: 100%;

        border_radius: co.radius.small;
        background: co.brushes.surface;
    }

    StateLayer {  
        border_radius: i_container.border_radius;
    }

    HorizontalLayout {  
        padding_left: co.spaces.medium;
        padding_right: co.spaces.medium;
        spacing: co.spaces.small;

        i_icon := MaterialIcon {
            y: (parent.height - height) / 2;
            icon_color: co.brushes.foreground;
            icon_size: co.icons.size_medium;
        }

        i_placeholder := Text {
            text <=> root.placeholder;
            vertical_alignment: center;
            color: co.brushes.border;
            font_size: co.typo.label_medium.size;
            font_weight: co.typo.label_medium.weight;
            font_family: co.typo.label_medium.family;
        }
    }
}