// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Spacer, Popup, SmallLabel, Switch,  Icon, CenterLayout, Theme, mi } from "_imports/coop_widgets.slint";

export component HeaderBarButton inherits TouchArea {
    in-out property <string> icon <=> i_icon.text;

    width: root.height;
    vertical_stretch: 1;
    horizontal_stretch: 0;

    i_container := Rectangle {
        border_radius: max(self.width, self.height) / 2;
        CenterLayout {  
            i_icon := Icon {  
                color: Theme.brushes.foreground;
                font_size:  Theme.icon.size.small;
            }
        }
    }

    states [
        pressed when root.pressed : {
            i_container.background: Theme.brushes.background.darker(Theme.state.pressed);
            i_icon.color: Theme.brushes.foreground.darker(Theme.state.pressed);
        }    
    ]
}

export component HeaderBar inherits Rectangle {
    callback logout();// <=> i_logout_button.clicked;

    min_width: 100px;
    height: Theme.sizes.small;
    background: Theme.brushes.background-alt;
    vertical-stretch: 0;

    GridLayout {  
        padding_left: Theme.spaces.medium;
        padding_right: Theme.spaces.medium;
        padding_top: 2px;
        padding_bottom: 2px;

        Text {  
            col: 2;
        }
      
        HorizontalLayout {  
            col: 3;
            spacing: Theme.spaces.small;

            @children
        }
    }

    Rectangle {
        y: parent.height - self.height;
        height: 1px;
        background: Theme.brushes.border;
    }

    i_menu := Popup {  
        x: root.width - 200px - Theme.spaces.medium;
        y: root.height + Theme.spaces.medium;
       
        width: 200px;
        opacity: 0.0;
       
        GridLayout {  
            padding: Theme.spaces.small;
            Row {
                SmallLabel {  
                    vertical_alignment: center;
                    text: "Window tilling";
                }

                Switch {}
            }

        }
    }
}

component HeaderBarExampel inherits Rectangle {
    width: 600px;
    height: 400px;

    HeaderBar {  

    y:0;  

    }
}