// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Spacer, Popup, SmallLabel, Switch, CenterLayout, Palette, Icography, State, Size, Space } from "@coop/lib.slint";

export component HeaderBarButton inherits TouchArea {
    in-out property <image> icon <=> i-icon.source;

    width: root.height;
    vertical-stretch: 1;
    horizontal-stretch: 0;

    states [
        pressed when root.pressed : {
            i-container.background: Palette.background.darker(State.pressed);
            i-icon.colorize: Palette.foreground.darker(State.pressed);
        }
    ]

    i-container := Rectangle {
        border-radius: max(self.width, self.height) / 2;

        CenterLayout {
            i-icon := Image {
                colorize: Palette.foreground;
                width:  Icography.small;
            }
        }
    }
}

export component HeaderBar inherits Rectangle {
    callback logout();// <=> i-logout-button.clicked;

    min-width: 100px;
    height: Size.small;
    background: Palette.background-alt;
    vertical-stretch: 0;

    GridLayout {
        padding-left: Space.medium;
        padding-right: Space.medium;
        padding-top: 2px;
        padding-bottom: 2px;

        Text {
            col: 2;
        }

        HorizontalLayout {
            col: 3;
            spacing: Space.small;

            @children
        }
    }

    Rectangle {
        y: parent.height - self.height;
        height: 1px;
        background: Palette.border;
    }

    i-menu := Popup {
        x: root.width - 200px - Space.medium;
        y: root.height + Space.medium;

        width: 200px;
        opacity: 0.0;

        GridLayout {
            padding: Space.small;
            Row {
                SmallLabel {
                    vertical-alignment: center;
                    text: "Window tilling";
                }

                Switch {}
            }

        }
    }
}