// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { RoundOutlineButton, Theme } from "_imports/coop_widgets.slint";

export component Launcher inherits HorizontalLayout {
    callback open(string);

    callback bring_to_front(int);

    in property <string> front_path;
    in-out property <[{ text: string, path: string} ]> entries;

    padding: Theme.spaces.medium;
    spacing: Theme.spaces.small;
    alignment: center;

    for entry[index] in root.entries : RoundOutlineButton {
        text: entry.icon;
        primary: entry.path == root.front_path;
        clicked => {  
            root.open(entry.path);
        }
    }
}