// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { RoundOutlineButton, Space } from "@coop/lib.slint";

export component Launcher inherits HorizontalLayout {
    in property <string> front_path;
    in-out property <[{ text: string, path: string} ]> entries;

    callback open(string);
    callback bring_to_front(int);

    padding: Space.medium;
    spacing: Space.small;
    alignment: center;

    for entry[index] in root.entries : RoundOutlineButton {
        // text: entry.icon;
        primary: entry.path == root.front_path;

        clicked => {
            root.open(entry.path);
        }
    }
}