// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Button, TextLine, CenterLayout, LargeTitle, ErrorLabel, FormElement, PopupBorder, Theme } from "_imports/coop_widgets.slint";

export component Login inherits Rectangle {
    pure callback login(string, string) -> bool;

    in-out property <image> logo <=> i_logo.source;
    in-out property <bool> login_error;

    background: Theme.brushes.background;

    CenterLayout {  
        PopupBorder {  
            i_layout := VerticalLayout {  
                padding: Theme.spaces.large;
                spacing: Theme.spaces.large;

                i_logo := Image {  
                    max_width: 100px;
                }

                FormElement {  
                    title: "User name";

                    i_user_name := TextLine {  
                        placeholder: "User";
                        text: "user";
                        has_error: root.login_error;
                    }
                }

                FormElement {  
                    title: "Password";

                    i_password := TextLine {  
                        placeholder: "Password";
                        text: "password";
                        input-type: password;
                        has_error: root.login_error;
                    }
                }

                i_label_error := ErrorLabel {
                    visible: root.login_error;
                    text: "User name or password wrong";
                }
    
                Button {  
                    text: "Login";
                    primary: true;
                    clicked => {  
                        root.login_error = !root.login(i_user_name.text, i_password.text);
                    }
                }
            }
        }
    }
}
