// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Button, LineEdit, CenterLayout, LargeTitle, ErrorLabel, FormElement, PopupBorder, Space, Palette } from "@coop/lib.slint";

export component Login inherits Rectangle {
    pure callback login(string, string) -> bool;

    in-out property <image> logo <=> i_logo.source;
    in-out property <bool> login_error;

    background: Palette.background;

    CenterLayout {
        PopupBorder {
            i_layout := VerticalLayout {
                padding: Space.large;
                spacing: Space.large;

                i_logo := Image {
                    max_width: 100px;
                }

                FormElement {
                    title: "User name";

                    i_user_name := LineEdit {
                        placeholder-text: "User";
                        text: "user";
                        has_error: root.login_error;
                    }
                }

                FormElement {
                    title: "Password";

                    i_password := LineEdit {
                        placeholder-text: "Password";
                        text: "password";
                        input-type: password;
                        has_error: root.login_error;
                    }
                }

                i_label_error := ErrorLabel {
                    visible: root.login_error;
                    text: "User name or password wrong";
                }

                Button {
                    text: "Login";
                    primary: true;

                    clicked => {
                        root.login_error = !root.login(i_user_name.text, i_password.text);
                    }
                }
            }
        }
    }
}
