// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { PageMinimized } from "page.slint";
import { RowTitle, ColumnTitle } from "../../pages/titles.slint";

import { Button, OutlineButton, RoundButton, RoundOutlineButton, Spacer, HorizontalSeparator,
    VerticalSpacerSmall, TextLine, CheckBox, Switch, mi, coop } from "../../_imports/coop_widgets.slint";

import { AppManager } from "../../app_manager.slint";

export BasicsPageMinimized := PageMinimized {
    GridLayout {  
        padding: coop.theme.spaces.large;
        spacing: coop.theme.spaces.medium;
       
        // Button
        Row {
            RowTitle {
                text: "Button";
            }
        }

        Row {
            Button {
                text: "Button";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            Button {
                primary: true;
                text: "Primary";
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerSmall {}
        }

        // OutlineButton
        Row {
            RowTitle {
                text: "OutlineButton";
            }
        }

        Row {
            OutlineButton {
                text: "OutlineButton";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            OutlineButton {
                text: "OutlineButton";
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerSmall {}
        }

        // RoundButton
        Row {
            RowTitle {
                text: "RoundButton";
            }
        }  

        Row {
            RoundButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundButton {
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerSmall {}
        }

        // RoundOutlineButton
        Row {
            RowTitle {
                text: "RoundOutlineButton";
            }
        }  

        Row {
            RoundOutlineButton {
                text: "A";
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            RoundOutlineButton {
                primary: true;
                icon: mi.plus;
                enabled: AppManager.widgets_enabled;
            }
        }

        Row {
            VerticalSpacerSmall {}
        }

        // TextLine
        Row {
            RowTitle {
                text: "TextLine";
            }
        }  

        Row {
            TextLine {
                enabled: AppManager.widgets_enabled;
                clickable: true;
                text <=> AppManager.text_line_one;

                clicked => { root.open_keyboard("text_line_one", text, placeholder, icon); }
            }

            Spacer {}

            TextLine {
                icon: mi.search;
                has-clear: true;
                enabled: AppManager.widgets_enabled;
                clickable: true;
                text <=> AppManager.text_line_two;

                clicked => { root.open_keyboard("text_line_two", text, placeholder, icon); }
            }
        }

        Row {
            VerticalSpacerSmall {}
        } 

        // Switch
        Row {
            RowTitle {
                text: "Switch";
            }
        }  

        Row {
            Switch {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            Switch {
                on_icon: mi.lightbulb;
                off_icon: mi.nights_stay;
                selected: !coop.dark_theme;
                selected_changed(selected) => {
                    coop.dark_theme = !selected;
                }
            }
        }

        Row {
            VerticalSpacerSmall {}
        } 

        // CheckBox
        Row {
            RowTitle {
                text: "CheckBox";
            }
        }  

        Row {
            CheckBox {
                enabled: AppManager.widgets_enabled;
            }

            Spacer {}

            CheckBox {
                text: "Widgets enabled";
                selected <=> AppManager.widgets_enabled;
            }
        }

        // Fills the remaining available space
        Row {
            Spacer {}
        }
    }
}