// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { AppManager } from "../../app_manager.slint"; 

import { HeaderBar, OutlineButton, CheckBox, Switch, Theme } from "../../_imports/coop_widgets.slint";

export component PageMinimized inherits GridLayout {
    callback open_keyboard(string, string, string, string);
    
    Flickable {  
        @children
    }   
}