// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";

// `ProgressBar` informs about current progress of ongoing process.
export ProgressBar := Rectangle { 
    // Represents the current progress.
    //
    // Must be a progress between 0.0 and 1.0.
    property <float> progress: 0.0;

    // If set to `true` the progress bar shows generic progress.
    property <bool> indeterminate;

    min-width: co.theme.sizes.large;
    height: co.theme.sizes.extra_extra_small;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    background: co.theme.brushes.surface;
    border_radius: co.theme.radius.extra_extra_small;
    clip: true;

    i_track := Rectangle {
        x: !indeterminate ? 0px : parent.width * mod(animation-tick(), 2s) / 2s;
        y: (parent.height - height) / 2;
        width: !indeterminate ?  parent.width * root.progress : root.width / 2;
        height: 100%;
        background: co.theme.brushes.primary;
        border_radius: root.border_radius;
    }
}

ProgressBarExample := Rectangle {
    width: 600px;
    height: 400px;
    background: co.theme.brushes.background;

    VerticalLayout {  
        padding: co.theme.spaces.large;
        spacing: co.theme.spaces.large;
        alignment: center;

        ProgressBar {  
            progress: 0.5;
        }

        ProgressBar {  
            indeterminate: true;
        }
    }
}