import { co } from "../co/co.slint";

import { Keyboard } from "keyboard_widget.slint";

export KeyboardPage := Rectangle {
    callback open_keyboard(string, string, string);
    
    property<bool> keyboard_open: false;

    open_keyboard(icon, placeholder, text) => {  
        i_keyboard.icon = icon;
        i_keyboard.placeholder = placeholder;
        i_keyboard.text = text;
        keyboard_open = true;
    }


    i_container := Rectangle {
        
        @children
    }

    i_keyboard := Keyboard {
        y: i_container.y + i_container.height;
      
        close => { root.keyboard_open = false; }
    }

    states [
        keyboard_open when root.keyboard_open : {
            i_container.y: -root.height;
        }
    ]

    transitions [  
        in keyboard_open : {
            animate i_container.y { duration: co.durations.fast; }
        }
        out keyboard_open : {
            animate i_container.y { duration:  co.durations.medium; }
        }
    ]
}