// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

import { co } from "../co/co.slint";

import { Keyboard } from "keyboard_widget.slint";

// `KeyboardPage` can switch between its children an a `Keyboard`.
export KeyboardPage := Rectangle {
    // Opens the keyboard
    callback open_keyboard(string, string, string, string);
    
    // Called after keyboard is closed.
    callback keyboard_closed(string, string);

    // FIXME: private with new syntax
    property <bool> keyboard_open: false;

    open_keyboard(key, text, placeholder, icon) => {  
        keyboard_open = true;
        i_keyboard.open(key, text, placeholder, icon);
    }

    i_container := Rectangle {
        @children
    }

    i_keyboard := Keyboard {
        y: i_container.y + i_container.height;
      
        close(key, text) => { 
            root.keyboard_open = false;
            root.keyboard_closed(key, text);
         }
    }

    states [
        keyboard_open when root.keyboard_open : {
            i_container.y: -root.height;
        }
    ]

    transitions [  
        in keyboard_open : {
            animate i_container.y { duration: co.durations.fast; }
        }
        out keyboard_open : {
            animate i_container.y { duration:  co.durations.medium; }
        }
    ]
}