// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SmallTitle } from "../components/label.slint";
import { coop } from "../coop/coop.slint";

// `FormElement` displays an title on its children.
export FormElement := VerticalLayout {
    // Defines the title of the element.
    in property <string> title <=> i_title.text;

    spacing: coop.theme.spaces.small;

    i_title := Text {
        horizontal-alignment: left;
    }

    @children  
}

import { TextLine } from "../widgets/text_line.slint";

FormElementTest := Rectangle {
    width: 300px;
    height: 200px;

    VerticalLayout {  
        padding: 16px;
        spacing: 8px;

        alignment: start;
        FormElement {   
            title: "Name";
    
            TextLine { 

            }
        }

        FormElement {   
            title: "Address";
    
            TextLine { }
        }
    }
}