// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SmallTitle } from "../components/label.slint";
import { Theme } from "../coop/theme.slint";

// `FormElement` displays an title on its children.
export component FormElement inherits VerticalLayout {
    // Defines the title of the element.
    in property <string> title <=> i_title.text;

    spacing: Theme.spaces.small;

    i_title := Text {
        horizontal-alignment: left;
    }

    @children  
}