// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Space } from "../styling.slint";

export component Spacer inherits Rectangle {}

export component VerticalSpacerSmall inherits Spacer {
    height: Space.small;
}

export component VerticalSpacerMedium inherits Spacer {
    height: Space.medium;
}

export component VerticalSpacerLarge inherits Spacer {
    height: Space.large;
}

export component HorizontalSpacerSmall inherits Spacer {
    width: Space.small;
}

export component HorizontalSpacerMedium inherits Spacer {
    width: Space.medium;
}

export component HorizontalSpacerLarge inherits Spacer {
    width: Space.large;
}