// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// `BookPage` defines a book page with  `title`, `text` and page `number`.
export component BookPage inherits Rectangle {
    // Defines the title of the page.
    in property <string> title <=> i_title.text;

    // Defines the color of the title label.
    in property <brush> title_color <=> i_title.color;

    // Defines the font size of the title label.
    in property <length> title_font_size <=> i_title.font_size;

    // Defines the font weight of the title label.
    in property <int> title_font_weight <=> i_title.font_weight;

    // Defines the font family of the title label.
    in property <string> title_font_family <=> i_title.font_family;

    // Defines the page number.
    in property <int> number;

    // Defines the color of the page number label.
    in property <brush> number_color <=> i_number.color;

    // Defines the font size of the page number label.
    in property <length> number_font_size <=> i_number.font_size;

    // Defines the font weight of the page number label.
    in property <int> number_font_weight <=> i_number.font_weight;

    // Defines the font family of the page number label.
    in property <string> number_font_family <=> i_number.font_family;

    // Defines the horizontal alignment of the page number label.
    in property <TextHorizontalAlignment> number_alignment <=> i_number.horizontal_alignment;

    // Defines the spacing between title label, separator, text label and number label.
    in property <length> spacing: 4px;

    // Defines the color of the title separator bar.
    in property <brush> separator_color <=> i_separator.background;
  
    padding: 8px;
    background: white;
    horizontal-stretch: 1;

    layout := Rectangle {  
        i_title := Text {
            x: root.padding;
            y: root.padding;
            width: root.width - 2 * root.padding;
            color: black;
            horizontal_alignment: left;
            overflow: elide;
            vertical_stretch: 0;
        }

        i_separator := Rectangle {
            x: root.padding;
            y: i_title.y + i_title.height + root.spacing;
            width: i_title.width;
            background: black;
            height: 1px;
            vertical_stretch: 0;
            visible: i_title.text != "";
        }

        i_layout := VerticalLayout {  
            x: root.padding;
            y: i_separator.y + i_separator.height + root.spacing;
            width: i_title.width;
            height: i_number.y - self.y;

            @children
        }

        i_number := Text {
            width: i_title.width;
            x: root.padding;
            y: root.height - self.height - root.padding;
            color: black;
            text: root.number;
            vertical_stretch: 0;
        }
    }
}