// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Palette } from "../styling/styling.slint";

export component CoopWindow inherits Window {
    in-out property <bool> dark-color-scheme <=> Palette.dark-color-scheme;
    in-out property <brush> accent <=> Palette.accent;
    in-out property <brush> on-accent <=> Palette.on-accent;

    background: Palette.background;
}