// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../coop/theme.slint";

// `CoopWindow` is a default window that uses the background of the `Theme` theme.
export component CoopWindow inherits Window {
    // Set to `true` to use the dark theme.
    in-out property <bool> dark <=> Theme.dark;

    //  Defines the accent color of the theme.
    in-out property <brush> accent_color <=> Theme.accent_color;

    // Defines the on accent color of the theme.
    in-out property <brush> on_accent_color <=> Theme.on_accent_color;

    background: Theme.brushes.background;
}