// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { coop } from "../coop/coop.slint";

// `CoopWindow` is a default window that uses the background of the `coop` theme.
export CoopWindow := Window {
    // Set to `true` to use the dark theme.
    in-out property <bool> dark_theme <=> coop.dark_theme;

    //  Defines the accent color of the theme.
    in-out property <brush> accent_color <=> coop.accent_color;

    // Defines the on accent color of the theme.
    in-out property <brush> on_accent_color <=> coop.on_accent_color;

    background: coop.theme.brushes.background;
}