// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT
import { Theme } from "../coop/theme.slint";

// `Icon` is a text component that uses the `ForkAwesome` font.
export component Icon inherits Text {
    font_family: Theme.icon.font_family;
    font_size: Theme.icon.size.small;
    color: Theme.brushes.foreground;
    vertical_stretch: 0;
    horizontal_stretch: 0;
}