// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Palette, Typography, TextStyle } from "../styling.slint";

export component SmallLabel inherits Text {
    color: Palette.foreground;
    font-size: Typography.small-label.font-size;
    font-weight: Typography.small-label.font-weight;
}

export component MediumLabel inherits Text {
    color: Palette.foreground;
    font-size: Typography.small-label.font-size;
    font-weight: Typography.small-label.font-weight;
}

export component LargeLabel inherits Text {
    color: Palette.foreground;
    font-size: Typography.large-label.font-size;
    font-weight: Typography.small-label.font-weight;
}

export component ErrorLabel inherits Text {
    font-size: Typography.small-label.font-size;
    font-weight: Typography.small-label.font-weight;
}

export component SmallTitle inherits Text {
    color: Palette.foreground;
    font-size: Typography.small-title.font-size;
    font-weight: Typography.small-title.font-weight;
}

export component MediumTitle inherits Text {
    color: Palette.foreground;
    font-size: Typography.medium-title.font-size;
    font-weight: Typography.medium-title.font-weight;
}

export component LargeTitle inherits Text {
    color: Palette.foreground;
    font-size: Typography.large-title.font-size;
    font-weight: Typography.large-title.font-weight;
}

export component ExtraLargeTitle inherits Text {
    color: Palette.foreground;
    font-size: Typography.extra-large-title.font-size;
    font-weight: Typography.extra-large-title.font-weight;
}