// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../coop/theme.slint";

// `PopupBorder` can used to draw border and background of a `Popup`.
export component PopupBorder inherits Rectangle {
    background: Theme.brushes.background;
    border_radius: Theme.radius.medium;
    border_width: 1px;
    border_color: Theme.brushes.border;
    clip: true;
}

// `Popup` is used to show a popup overlay.
export component Popup inherits PopupWindow {
    PopupBorder {  
        @children
    }
}