// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Radius, Palette } from "../styling.slint";

export component PopupBorder inherits Rectangle {
    background: Palette.background;
    border-radius: Radius.medium;
    border-width: 1px;
    border-color: Palette.border;
    clip: true;
    drop-shadow-color: Palette.shadow;
    drop-shadow-blur: 16px;
    drop-shadow-offset-y: 4px;
}

export component Popup inherits PopupWindow {
    PopupBorder {
        @children
    }
}