// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow } from "coop-window.slint";
import { Palette } from "../styling/styling.slint";
import { Button } from "../widgets/button.slint";
import { Switch } from "../widgets/checkables.slint";

export component ThemedWindow inherits CoopWindow {
    background <=> Palette.background;

    out property <brush> background-alt <=> Palette.background-alt;
    out property <brush> foreground <=> Palette.foreground;
    out property <brush> foreground-disabled <=> Palette.foreground-disabled;
    out property <brush> surface <=> Palette.surface;
    out property <brush> surface-disabled <=> Palette.surface-disabled;
    out property <brush> on-surface <=> Palette.on-surface;
    out property <brush> primary <=> Palette.primary;
    out property <brush> on-primary <=> Palette.on-primary;
    out property <brush> border <=> Palette.border;
    out property <brush> border-disabled <=> Palette.border-disabled;
    out property <brush> state <=> Palette.state;
    out property <brush> shadow <=> Palette.shadow;
    out property <brush> error <=> Palette.error;
}