// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow } from "coop_window.slint";
import { Button } from "../widgets/button.slint";
import { Switch } from "../widgets/selectables.slint";
import { coop, Theme } from "../coop/coop.slint";

// `ThemeWindow` provides the possibility to adjust the theming of the `coop_widgets`.
export ThemeWindow := CoopWindow {
    // Can be used to override style definitions of the `coop_widgets` theme.
    in property <Theme> theme_override: coop.theme;
}

ThemeWindowExample := ThemeWindow {
    title: "Theme window";
    width: 600px; 
    height: 400px;

    theme_override: {
        brushes: {
            background: coop.dark_theme ? #04dc82: #2d00e1,
            foreground: coop.dark_theme ? #dfdfdf: #2d2d2d,
            foreground_disabled: coop.dark_theme ? #7b7b7b: #a0a0a0,
            surface: coop.dark_theme ? #505050: #BDBDBD,
            surface_disabled: coop.dark_theme ? #3d3d3d: #d2d2d2,
            on_surface: coop.dark_theme ? #212121: #dfdfdf,
            primary: coop.accent_color,
            on_primary: coop.on_accent_color,
            border: coop.dark_theme ? #7e7e7e: #505050,
            border_disabled: coop.dark_theme ? #494949: #c5c5c5,
            state: #000000,
        },
        durations: {
            slow: 500ms,
            medium: 250ms,
            fast: 150ms,
        },
        icons: {
            size_small: 12px,
            size_medium: 14px,
            size_large: 16px,
        },
        state: {
            hover: 0.2,
            pressed: 0.4,
            container_disabled: 0.38,
            content_disabled: 0.38,
        },
        sizes: {
            extra_extra_small: 4px,
            extra_small: 20px,
            small: 26px,
            medium: 32px,
            large: 44px,
        },
        radius: {
            extra_extra_small: 2px,
            extra_small: 4px,
            small: 6px,
            medium: 8px,
            large: 16px,
        },
        spaces: {
            extra_small: 2px,
            small: 4px,
            medium: 8px,
            large: 16px,
        },
        typo: {
            small_label: {
                size: 12px,
                weight: 400
            },
            medium_label: {
                size: 12px,
                weight: 500      
            },
            large_label: {
                size: 14px,
                weight: 500
            },
            small_title: {
                size: 16px,
                weight: 500      
            },
            medium_title:{
                size: 20px,
                weight: 500      
            },
            large_title: {
                size: 24px,
                weight: 500      
            },
        }
    };

    VerticalLayout {  
        padding: coop.theme.spaces.medium;
        spacing: coop.theme.spaces.small;

        Button {
            text: "Click me";
        }

        Switch {
            selected <=> coop.dark_theme;
        }
    }
}