// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow } from "coop_window.slint";
import { Button } from "../widgets/button.slint";
import { Switch } from "../widgets/selectables.slint";
import { Theme, Brushes } from "../coop/theme.slint";

// `CoopWindow` provides the possibility to adjust the theming of the `coop_widgets`.
export component ThemedWindow inherits CoopWindow {
    in property <Brushes> brushes <=> Theme.brushes;
}