// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Book } from "/Users/flovansl/Projects/flovansl/co_sl/widgets/book_flip/ui/book.slint";
import { BookPage } from "/Users/flovansl/Projects/flovansl/co_sl/widgets/book_flip/ui/book_page.slint";
import { TextPage } from "/Users/flovansl/Projects/flovansl/co_sl/widgets/book_flip/ui/text_page.slint";

export { Book, BookPage, TextPage } 