// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { TextStyle } from "../structs.slint";

export global Typography {
    out property <TextStyle> small-label: {
        font-size: 12 * 0.0769rem,
        font-weight: 400
    };
    out property <TextStyle> medium-label: {
        font-size: 12 * 0.0769rem,
        font-weight: 500
    };
    out property <TextStyle> large-label: {
        font-size: 14 * 0.0769rem,
        font-weight: 500
    };
    out property <TextStyle> small-title: {
        font-size: 16 * 0.0769rem,
        font-weight: 500
    };
    out property <TextStyle> medium-title:{
        font-size: 20 * 0.0769rem,
        font-weight: 500
    };
    out property <TextStyle> large-title: {
        font-size: 24 * 0.0769rem,
        font-weight: 500
    };
    out property <TextStyle> extra-large-title: {
        font-size: 48 * 0.0769rem,
        font-weight: 500
    };
}