// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { RowTitle, ColumnTitle } from "titles.slint";

import { StandardTableView, ScrollView, ListView, GroupListView, Switch, StandardListView, TabView,
    Button } from "@coop/widgets.slint";
import { HeaderBar } from "@coop/building-blocks.slint";
import { HorizontalSeparator, VerticalSpacerMedium, VerticalBox, Spacer } from "@coop/layouts.slint";
import { Palette, Icons, ColorVariant, Space } from "@coop/styling.slint";
import { GroupListViewItem, TabItem } from "@coop/structs.slint";

export global ListPageAdapter {
    callback close-tab-item(/* index */ int);

    in property <[TabItem]> tab-items: [
        { icon: Icons.add, text: "Tab 1" },
        { icon: Icons.add, text: "Tab 2" },
        { icon: Icons.add, text: "Tab 3" },
    ];
}

export component ListPage inherits GridLayout {
    in property <length> header-offset <=> i-header-bar.offset;

    preferred-width: 100%;
    preferred-height: 100%;

    Row {
        i-header-bar := HeaderBar {
            title: "Lists";

            VerticalLayout {
                alignment: center;

                Switch {
                    on-icon: Icons.light-mode;
                    off-icon: Icons.mode-night;
                    checked: !Palette.dark-color-scheme;

                    toggled(checked) => {
                        Palette.set-color-variant(checked ? ColorVariant.Light : ColorVariant.Dark);
                    }
                }
            }
        }
    }

    Row {
        GridLayout {
            padding: Space.large;
            spacing: Space.medium;

            // Lists
            Row {
                RowTitle {
                    text: @tr("ListViews");
                }
            }

            Row {
                ColumnTitle {
                    text: @tr("ListView");
                }

                ColumnTitle {
                    text: @tr("StandardListView");
                }

                ColumnTitle {
                    text: @tr("GroupListView");
                }

                ColumnTitle {
                    text: @tr("ScrollView");
                }
            }

            Row {
                HorizontalSeparator {
                    colspan: 4;
                }
            }

            Row {
                ListView {
                    for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] : HorizontalLayout {
                        Text {
                            color: Palette.foreground;
                            text: @tr("Item {}", i);
                        }
                     }
                }

                StandardListView {
                    height: 100px;

                    model: [
                        { leading-icon: Icons.add, text: "Item 1" },
                        { leading-icon: Icons.add, text: "Item 2" },
                        { leading-icon: Icons.add, text: "Item 3" },
                        { leading-icon: Icons.add, text: "Item 4" },
                        { leading-icon: Icons.add, text: "Item 5" },
                        { leading-icon: Icons.add, text: "Item 6" },
                    ];
                }

                GroupListView {
                    height: 100px;
                    property <GroupListViewItem> group: {
                        text: "Group 1",
                        items: [
                            { text: "Item 1" },
                            { text: "Item 2" },
                            { text: "Item 3" },
                        ]
                    };
                    property <GroupListViewItem> group-two: {
                        text: "Group 2",
                        items: [
                            { text: "Item 1" },
                            { text: "Item 2" },
                            { text: "Item 3" },
                        ]
                    };
                    model: [self.group, self.group-two];
                }

                ScrollView {
                    height: 100px;

                    VerticalLayout {
                        spacing: 4px;

                        for i in [0, 1, 2, 3, 4, 5, 6, 7] : Rectangle {
                            height: 50px;
                            background: mod(i, 2) == 0 ? black : gray;
                        }
                    }
                }
            }

            Row {
                VerticalSpacerMedium {}
            }

             // StandardTableView
             Row {
                RowTitle {
                    text: "StandardTableView";
                }
            }

            Row {
                HorizontalSeparator {
                    colspan: 4;
                }
            }

            Row {
                StandardTableView {
                    zebra-pattern: true;
                    colspan: 4;
                    columns: [
                        { horizontal-stretch: 0, min-width: 32px },
                        { title: @tr("Name"), horizontal-stretch: 1 },
                        { title: @tr("Date Modified"), horizontal-stretch: 0, min-width: 128px },
                        { title: @tr("Size"), horizontal-stretch: 0, min-width: 96px },
                        { title: @tr("Kind"), horizontal-stretch: 0, min-width: 128px },
                    ];
                    rows: [
                        { model: [ { leading-icon: Icons.folder, highlighted: true }, { highlighted: true, text: "src" }, { text: "2022.11.10" }, { text: "---" }, { text: "Folder" }, ] },
                        { model: [ { leading-icon: Icons.description }, { text: "test.slint" }, { text: "2022.11.10" }, { text: "17 KB" }, { text: "Document" }, ] },
                        { model: [ { leading-icon: Icons.description }, { text: "test2.slint" }, { text: "2022.11.10" }, { text: "17 KB" }, { text: "Document" }, ] },
                        { model: [ { leading-icon: Icons.description }, { text: "test3.slint" }, { text: "2022.11.10" }, { text: "17 KB" }, { text: "Document" }, ] },
                        { model: [ { leading-icon: Icons.description }, { text: "test4.slint" }, { text: "2022.11.10" }, { text: "17 KB" }, { text: "Document" }, ] },
                    ];
                }
            }

            Row {
                VerticalSpacerMedium {}
            }

            // TabView
            Row {
                RowTitle {
                    text: "TabView";
                }
            }

            Row {
                HorizontalSeparator {
                    colspan: 4;
                }
            }

            Row {
                i-tab-view := TabView {
                    colspan: 4;

                    model: ListPageAdapter.tab-items;

                    for tab-item[index] in self.model : Rectangle {
                        if (index == i-tab-view.current-item) : VerticalBox {
                            alignment: start;

                            ColumnTitle {
                                text: tab-item.text;
                            }
                        }
                    }

                    close-item(index) => {
                        ListPageAdapter.close-tab-item(index);
                    }
                }
            }

            // Fills the remaining available space
            Row {
                Spacer {}
            }
        }
    }
}