// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { AppManager } from "../app-manager.slint";

import { HeaderBar, OutlineButton, CheckBox, Switch, ScrollView, Icons, ComboBox, Palette, ColorTheme, ColorScheme } from "@coop/lib.slint";

export component Page inherits GridLayout {
    in-out property <string> title <=> i-header-bar.title;
    in-out property <bool> keyboard_check_box: true;
    in-out property <bool> disabled_check_box: true;
    in property <length> header-offset <=> i-header-bar.offset;

    Row {
        i-header-bar := HeaderBar {
            if (root.keyboard_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Keyboard";
                checked <=> AppManager.keyboard_enabled;
            }

            if (root.disabled_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Widgets";
                checked <=> AppManager.widgets_enabled;
            }

            ComboBox {
                selected (index) => {
                    if (index == 0) {
                        Palette.set-color-theme(ColorTheme.Coop);
                        return;
                    }

                    if (index == 1) {
                        Palette.set-color-theme(ColorTheme.Cosmic);
                    }

                    if (index == 2) {
                        Palette.set-color-theme(ColorTheme.Cupertino);
                    }
                }

                width: 94px;
                placeholder-text: @tr("Select theme:");
                current-index: Palette.current-color-theme == ColorTheme.Coop ? 0 : Palette.current-color-theme == ColorTheme.Cosmic ? 1 : 2;

                model: [
                    { text: "Coop" },
                    { text: "Cosmic" },
                    { text: "Cupertino" },
                ];
            }

            VerticalLayout {
                alignment: center;

                Switch {
                    toggled(checked) => {
                        Palette.set-color-variant(checked ? ColorScheme.Light : ColorScheme.Dark);
                    }

                    on_icon: Icons.mode-night;
                    off_icon: Icons.light-mode;
                    checked: !Palette.dark-color-scheme;
                }
            }
        }
    }

    Row {
        ScrollView {
            @children
        }
    }
}