// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { AppManager } from "../app-manager.slint";

import { HeaderBar, OutlineButton, CheckBox, Switch, ScrollView, Icons, ComboBox, Palette, ColorTheme, ColorVariant } from "../_imports/coop-widgets.slint";

export component Page inherits GridLayout {
    in-out property <string> title <=> i_header_bar.title;
    in-out property <bool> keyboard_check_box: true;
    in-out property <bool> disabled_check_box: true;

    Row {
        i_header_bar := HeaderBar {
            if (root.keyboard_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Keyboard enabled";
                checked <=> AppManager.keyboard_enabled;
            }

            if (root.disabled_check_box) : CheckBox {
                y: (parent.height - self.height) / 2;
                text: "Widgets enabled";
                checked <=> AppManager.widgets_enabled;
            }

            ComboBox {
                width: 128px;
                placeholder-text: @tr("Select theme:");
                current-index: Palette.current-color-theme == ColorTheme.Coop ? 0 : 1;

                model: [
                    { text: "Coop" },
                    { text: "Cosmic" },
                ];

                selected (index) => {
                    if (index == 0) {
                        Palette.set-color-theme(ColorTheme.Coop);
                        return;
                    }

                    if (index == 1) {
                        Palette.set-color-theme(ColorTheme.Cosmic);
                    }
                }
            }

            VerticalLayout {
                alignment: center;

                Switch {
                    on_icon: Icons.mode-night;
                    off_icon: Icons.light-mode;
                    checked: !Palette.dark-color-scheme;

                    toggled(checked) => {
                        Palette.set-color-variant(checked ? ColorVariant.Light : ColorVariant.Dark);
                    }
                }
            }
        }
    }

    Row {
        ScrollView {
            @children
        }
    }
}