// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { BasicsPage } from "basics-page.slint";
import { BookFlipPage } from "book-flip-page.slint";
import { BrushesPage } from "brushes-page.slint";
import { IconPage } from "icon-page.slint";
import { ListPage } from "list-page.slint";
import { TypoPage } from "typo-page.slint";

export { BasicsPage }
export { BookFlipPage }
export { BrushesPage }
export { IconPage }
export { TypoPage }
export { ListPage }