// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { HeaderBar, ScrollView } from "_imports/coop-widgets.slint";

export global MessageViewAdapter  {
    in-out property <string> title: "Internal";
}

export component MessageView inherits Rectangle {
    horizontal-stretch: 1;

    VerticalLayout {
        i_header := HeaderBar {
            title:  MessageViewAdapter.title;
            vertical-stretch: 0;
        }

        ScrollView {
            vertical-stretch: 1;

            VerticalLayout {

            }
        }
    }
}