// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { SideBar, GroupListView, Space, LineEdit, GroupListViewItem, Icons } from "_imports/coop-widgets.slint";

export global SideBarViewAdapter  {
    in-out property <string> channel_search;
    in-out property<[GroupListViewItem]> channels;
}

export component SideBarView inherits SideBar {
    HorizontalLayout {
        padding_left: Space.large;
        padding_right: Space.large;
        padding_bottom: Space.large;
        i_search := LineEdit {
            min_width: 20px;
            placeholder-text: "Find channel";
            text <=> SideBarViewAdapter.channel_search;
            // icon: Icons.fa_var_search;
            // action_icon: Icons.fa_var_remove;
            action => { self.text = ""; }
        }
    }

    i_navigation := GroupListView {
        model <=> SideBarViewAdapter.channels;

        current_item_changed => {
            root.expanded = false;
        }
    }
}