// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { SideBar, ListView, TextLine, ParentItemModel, coop, mi } from "_imports/coop_widgets.slint";

export global SideBarViewAdapter := {
    property <string> channel_search;
    property<[ParentItemModel]> channels;
}

export SideBarView := SideBar {
    width: 200px;
    height: 100%;
    horizontal-stretch: 0;

    HorizontalLayout {  
        padding: coop.theme.spaces.large;
        i_search := TextLine {
            placeholder: "Find channel";
            text <=> SideBarViewAdapter.channel_search;
            icon: mi.search;
            has_clear: true;
        }
    }
   
    i_navigation := ListView {      
        model <=> SideBarViewAdapter.channels;
    }
}