// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { SideBar, List, TextLine, GroupItemModel, Theme, Icons } from "_imports/coop_widgets.slint";

export global SideBarViewAdapter  {
    in-out property <string> channel_search;
    in-out property<[GroupItemModel]> channels;
}

export component SideBarView inherits SideBar {
    HorizontalLayout {  
        padding_left: Theme.spaces.large;
        padding_right: Theme.spaces.large;
        padding_bottom: Theme.spaces.large;
        i_search := TextLine {
            min_width: 20px;
            placeholder: "Find channel";
            text <=> SideBarViewAdapter.channel_search;
            icon: Icons.fa_var_search;
            action_icon: Icons.fa_var_remove;
            action => { self.text = ""; }
        }
    }
   
    i_navigation := List {      
        model <=> SideBarViewAdapter.channels;

        current_item_changed => {  
            root.expanded = false;
        }
    }
}