// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { SideBar, List, TextLine, GroupItemModel, coop, mi } from "_imports/coop_widgets.slint";

export global SideBarViewAdapter := {
    property <string> channel_search;
    property<[GroupItemModel]> channels;
}

export SideBarView := SideBar {
    HorizontalLayout {  
        padding_left: coop.theme.spaces.large;
        padding_right: coop.theme.spaces.large;
        padding_bottom: coop.theme.spaces.large;
        i_search := TextLine {
            min_width: 20px;
            placeholder: "Find channel";
            text <=> SideBarViewAdapter.channel_search;
            icon: mi.search;
            action_icon: mi.clear;
            action => { text = ""; }
        }
    }
   
    i_navigation := List {      
        model <=> SideBarViewAdapter.channels;

        current_item_changed => {  
            root.expanded = false;
        }
    }
}