// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: GPL-3.0-only

import { Button, VerticalBox } from "std-widgets.slint";

export AppWindow := Window {
    property <int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                request-increase-value();
            }
        }
     }
}
