// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { VirtualKeyboard, VirtualKeyboardAdapter } from "@coop/widgets.slint";
import { ResponsiveContainer } from "@coop/building-blocks.slint";
import { Duration, Palette, Icons  } from "@coop/styling.slint";
import { OverlayTouchArea, CoopWindow } from "@coop/components.slint";
import { TabItem, GroupListViewItem } from "@coop/structs.slint";
import { ListPageAdapter } from "pages/pages.slint";
import { AppManager } from "app-manager.slint";
import { SideBarView } from "side-bar-view.slint";

import { Pages } from "pages.slint";

export { VirtualKeyboardAdapter }
export { AppManager }
export { ListPageAdapter }
export { TabItem }

export component App inherits CoopWindow {
    private property <GroupListViewItem> widgets: {
        text: "Widgets",
        items: [
            { leading-icon: Icons.home, text: "Basics", highlighted: true },
            { leading-icon: Icons.list, text: "Lists", highlighted: true },
            { leading-icon: Icons.pin, text: "TextEdit", highlighted: true },
            { leading-icon: Icons.book, text: "Book flip", highlighted: true },
        ]
    };

    private property <GroupListViewItem> resources: {
        text: "Resources",
        items: [
            { leading-icon: Icons.brush, text: "Brushes", highlighted: true },
            { leading-icon: Icons.format-size, text: "Typography", highlighted: true },
        ]
    };
    private property <{ parent: int, item: int }> current-navigation-item;

    min-width: 400px;
    min-height: 600px;
    preferred-width: 800px;
    title: "Gallery";
    background: Palette.background;

    i-responsive-container := ResponsiveContainer {
        reference-width: parent.width;

        if (!i-responsive-container.on-break) : HorizontalLayout {
            SideBarView {
                title: root.title;
                navigation-items: [root.widgets, root.resources];
                resizable: true;
                current-item <=> root.current-navigation-item;
            }

            Pages {
                current-navigation-item: root.current-navigation-item;
            }
        }

        if (i-responsive-container.on-break) : Rectangle {
            width: 100%;
            height: 100%;

            Pages {
                current-navigation-item: root.current-navigation-item;
                header-offset: i-responsive-container.expand-button-width;
            }

            if (i-responsive-container.expand-shrunken) : OverlayTouchArea {
                clicked => {
                    i-responsive-container.expand-shrunken = false;
                }
            }

            SideBarView {
                current-item-changed => {
                    i-responsive-container.expand-shrunken = false;
                }

                x: i-responsive-container.expand-shrunken ? 0 : -self.width;
                title: root.title;
                navigation-items: [root.widgets, root.resources];
                current-item <=> root.current-navigation-item;

                animate x { duration: Duration.fast;}
            }
        }
    }
}