// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SideBar, GroupListView, GroupListViewItem } from "_imports/coop-widgets.slint";

export component SideBarView inherits SideBar {
    in-out property <[GroupListViewItem]> navigation-items <=> i-navigation.model;
    in-out property <{ parent: int, item: int }> current-item <=> i-navigation.current-item;

    i-navigation := GroupListView {
        vertical-stretch: 1;

        current-item-changed => {
            root.expanded = false;
         }
    }
}