// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SideBar, GroupListView, GroupListViewItem } from "@coop/lib.slint";

export component SideBarView inherits SideBar {
    callback current-item-changed <=> i-navigation.current-item-changed;

    in-out property <[GroupListViewItem]> navigation-items <=> i-navigation.model;
    in-out property <{ parent: int, item: int }> current-item <=> i-navigation.current-item;

    forward-focus: i-navigation;

    i-navigation := GroupListView {
        vertical-stretch: 1;
        current-item: { item: 0, parent: 0 };
    }
}