// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { SideBar, ListView, TextLine, ParentItemModel, co, mi } from "_imports/co_widgets.slint";

export global AppSideBarBridge := {
    property <string> channel_search;
    property<[ParentItemModel]> channels;
}

export AppSideBar := SideBar {
    width: 200px;
    height: 100%;

    HorizontalLayout {  
        padding: co.theme.spaces.large;
        i_search := TextLine {
            placeholder: "Find channel";
            text <=> AppSideBarBridge.channel_search;
            icon: mi.search;
            has_clear: true;
        }
    }
   
    i_navigation := ListView {      
        model <=> AppSideBarBridge.channels;
    }
}