// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow, Keyboard, KeyboardAdapter, Theme } from "../_imports/coop_widgets.slint";
import { BasicsPageMinimized } from "pages/pages.slint";
import { AppManager } from "../app_manager.slint"; 

export { KeyboardAdapter, Theme }
export { AppManager }

export component App inherits CoopWindow {
    in-out property <bool> keyboard_open: false;
    in-out property <string> keyboard_text;
    in-out property <string> keyboard_key;
    in-out property <string> keyboard_placeholder;
    in-out property <string> keyboard_icon;
    title: "Widgets gallery";

    Rectangle {  
        width: 100%;
        height: 100%;
        background: Theme.brushes.background;

        if(!root.keyboard_open) : BasicsPageMinimized {
            open_keyboard(key, text, placeholder, icon) => {    
                root.keyboard_text = text;
                root.keyboard_key = key;
                root.keyboard_placeholder = placeholder;
                root.keyboard_icon = root.icon;
                root.keyboard_open = true;
            }
        }
    
        if(root.keyboard_open) : Keyboard {
            text: root.keyboard_text;
            icon: root.keyboard_icon;
            placeholder: root.keyboard_placeholder;
            // key: root.keyboard_key;

            close(key, text) => {  
                AppManager.update_text(key, self.text);
                root.keyboard_open = false;
            }
        }
    }
}