// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow, Keyboard, KeyboardAdapter, coop } from "../_imports/coop_widgets.slint";
import { BasicsPageMinimized } from "pages/pages.slint";
import { AppManager } from "../app_manager.slint"; 

export { KeyboardAdapter, coop }
export { AppManager }

export App := CoopWindow {
    property <bool> keyboard_open: false;
    property <string> keyboard_text;
    property <string> keyboard_key;
    property <string> keyboard_placeholder;
    property <string> keyboard_icon;
    title: "Widgets gallery";

    Rectangle {  
        width: 100%;
        height: 100%;
        background: coop.theme.brushes.background;

        if(!keyboard_open) : BasicsPageMinimized {
            open_keyboard(key, text, placeholder, icon) => {    
                keyboard_text = text;
                keyboard_key = key;
                keyboard_placeholder = placeholder;
                keyboard_icon = icon;
                keyboard_open = true;
            }
        }
    
        if(keyboard_open) : Keyboard {
            text: root.keyboard_text;
            icon: root.keyboard_icon;
            placeholder: root.keyboard_placeholder;
            // key: root.keyboard_key;

            close(key, text) => {  
                AppManager.update_text(key, text);
                keyboard_open = false;
            }
        }
    }
}