# SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
# SPDX-License-Identifier: MIT

[book]
authors = ["Florian Blasius"]
language = "en"
multilingual = false
src = "src"
title = "coop_widgets 0.1 reference"
