// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { BookmarksAdapter } from "views/bookmarks-view.slint";
export { BookmarksAdapter }

import { DialogView, DialogAdapter } from "views/dialog-view.slint";
export { DialogAdapter }

import { FilesAdapter } from "views/files-view.slint";
export { FilesAdapter }

import { GamesAdapter, GameSettingsAdapter } from "views/games-view.slint";
export { GamesAdapter, GameSettingsAdapter }

import { ImageAdapter } from "views/image-view.slint";
export { ImageAdapter }

import { TextEditorAdapter } from "views/text-editor-view.slint";
export { TextEditorAdapter }

import { ListViewItem, CoopWindow, Icons, GroupListViewItem, LoadingIndicator } from "@coop/lib.slint";
export { ListViewItem, Icons, GroupListViewItem }

import { OverlayTouchArea } from "@coop/components.slint";
import { Duration } from "@coop/styling.slint";
import { ResponsiveContainer } from "@coop/building-blocks.slint";
import { View, Views } from "views.slint";
import { SideBarView } from "views/sidebar-view.slint";

export global MainAdapter {
    in property <View> active-view: View.Files;
    in property <bool> loading;
}

export component MainWindow inherits CoopWindow {
    title: "coop local";
    min-width: 316px;
    min-height: 400px;
    preferred-width: 600px;

    i-responsive-container := ResponsiveContainer {
        reference-width: parent.width;

        if (!i-responsive-container.on-break) : HorizontalLayout {
            SideBarView {
                resizable: true;
                collapse-title: true;
                window-height: root.height;
            }

            Views {
                active-view: MainAdapter.active-view;
                window-height: root.height;
            }
        }

        if (i-responsive-container.on-break) : Rectangle {
            width: 100%;
            height: 100%;

            Views {
                active-view: MainAdapter.active-view;
                header-offest: i-responsive-container.expand-button-width;
                window-height: root.height;
            }

            if (i-responsive-container.expand-shrunken) : OverlayTouchArea {
                clicked => {
                    i-responsive-container.expand-shrunken = false;
                }
            }

            SideBarView {
                item-clicked => {
                    i-responsive-container.expand-shrunken = false;
                }

                x: i-responsive-container.expand-shrunken ? 0 : -self.width;
                window-height: root.height;

                animate x { duration: Duration.fast;}
            }
        }
    }

    DialogView {
        width: 100%;
        height: 100%;
    }

    if (MainAdapter.loading) : LoadingIndicator {}
}