// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { BookmarksView, BookmarksAdapter } from "views/bookmarks-view.slint";
export { BookmarksAdapter }

import { DialogView, DialogAdapter } from "views/dialog-view.slint";
export { DialogAdapter }

import { FilesView, FilesAdapter } from "views/files-view.slint";
export { FilesAdapter }

import { GamesView, GamesAdapter, GameSettingsAdapter } from "views/games-view.slint";
export { GamesAdapter, GameSettingsAdapter }

import { ImageView, ImageAdapter } from "views/image-view.slint";
export { ImageAdapter }

import { TextView, TextAdapter } from "views/text-view.slint";
export { TextAdapter }

import { ListViewItem, CoopWindow, Icons, GroupListViewItem, SideBar, LoadingIndicator } from "_imports/coop-widgets.slint";
export { ListViewItem, Icons, GroupListViewItem }

export enum ActiveView {
    Files,
    Image,
    Text,
    Games
}

export global MainAdapter {
    in property <ActiveView> active-view: ActiveView.Files;
    in property <bool> loading;
}

export component MainWindow inherits CoopWindow {
    title: "coop local";
    min-width: 316px;
    min-height: 400px;
    preferred-width: 600px;

    GridLayout {
        Rectangle {
            col: 1;

            if (MainAdapter.active-view == ActiveView.Files) : FilesView {
                window-height: root.height;
                width: 100%;
                height: 100%;
            }

            if (MainAdapter.active-view == ActiveView.Image) : ImageView {
                width: 100%;
                height: 100%;
            }

            if (MainAdapter.active-view == ActiveView.Text) : TextView {
                width: 100%;
                height: 100%;
            }

            if (MainAdapter.active-view == ActiveView.Games) : GamesView {
                width: 100%;
                height: 100%;
            }
        }

        SideBar {
            col: 0;
            parent-width: root.width;
            responsive: true;

            BookmarksView {
                window-height: root.height;
            }
        }
    }

    DialogView {
        width: 100%;
        height: 100%;
    }

    if (MainAdapter.loading) : LoadingIndicator {
        width: 100%;
        height: 100%;
    }
}