// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only


import { BookmarksView } from "views/bookmarks-view.slint";
import { DialogView } from "views/dialog-view.slint";
import { FilesView } from "views/files-view.slint";
import { GamesView } from "views/games-view.slint";
import { ImageView } from "views/image-view.slint";
import { TextEditorView } from "views/text-editor-view.slint";

export enum View {
    Files,
    Image,
    Text,
    Games
}

export component Views {
    in property <View> active-view: View.Files;
    in property <length> window-height;
    in property <length> header-offest;

    preferred-width: 100%;
    preferred-height: 100%;
    vertical-stretch: 1;
    horizontal-stretch: 1;

    if (root.active-view == View.Files) : FilesView {
        window-height: root.window-height;
        width: 100%;
        height: 100%;
        header-offest: root.header-offest;
    }

    if (root.active-view == View.Image) : ImageView {
        width: 100%;
        height: 100%;
        header-offest: root.header-offest;
    }

    if (root.active-view == View.Text) : TextEditorView {
        width: 100%;
        height: 100%;
        header-offest: root.header-offest;
    }

    if (root.active-view == View.Games) : GamesView {
        width: 100%;
        height: 100%;
        header-offest: root.header-offest;
    }
}