// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

export struct IconSize {
  // Defines the small icon size.
  small: length,

  // Defines the medium icon size.
  medium: length,

  // Defines the large icon size.
  large: length
}

// `Icons` provides icon settings and all icon unicodes.
export struct IconSet  {
   // Defines the sizes of an icon.
   size: IconSize,

   // Defines the icon font family.
   font_family: string,
}