// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// `Radius` defines the border radius.
export struct Radius  {
    // Defines the extra extra small border radius.
    extra_extra_small: length,

    // Defines the extra small border radius.
    extra_small: length,

    // Defines the small border radius.
    small: length,

    // Defines the medium border radius.
    medium: length,

    // Defines the large border radius.
    large: length,
}