// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// `Sizes` defines the widget and components sizes (width / height).
export struct Sizes := {
    // Defines the extra extra small size.
    extra_extra_small: length,

    // Defines the extra small size.
    extra_small: length,

    // Defines the small size.
    small: length,

    // Defines the medium size.
    medium: length,

    // Defines the large size.
    large: length,
}