// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// `States` defines opacity and brush.darker / brush.lighter.
export struct States := {
    // Defines hover float.
    hover: float,

    // Defines pressed float.
    pressed: float,

    // Defines container disabled float.
    container_disabled: float,

    // Defines content disabled float.
    content_disabled: float,
}