// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// `Font` defines the typography settings of a text.
export struct Font  {
    // Defines the text size.
    size: length,

    // Defines the font weight.
    weight: int,
}

// `Typo` defines the typography settings.
export struct Typo  {
    // Defines typo of small labels.
    small_label: Font,

    // Defines typo of medium labels.
    medium_label: Font,

    // Defines typo of large labels.
    large_label: Font,

    // Defines typo of small titles.
    small_title: Font,

    // Defines typo of medium titles.
    medium_title: Font,

    // Defines typo of large titles.
    large_title: Font,
}