// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { GroupListView, GroupListViewItem, ListViewItem, ContextMenu, Size, Space } from "@coop/lib.slint";

export global BookmarksAdapter {
    callback open-dir(/* parent */ int, /* item */ int);
    callback open-previous-dir();
    callback open-next-dir();
    callback get-item-context-menu(/* parent-row */ int, /* item-row */ int) -> [ListViewItem];
    callback item-context-menu-action(/* parent-row */ int, /* item-row */ int, /* spec */ string);
    callback selected-item() -> { parent: int, item: int };

    in property <[GroupListViewItem]> bookmarks;
}

export component BookmarksView {
    callback item-clicked();

    private property <int> item-context-menu-item-index;
    private property <int> item-context-menu-par-index;
    private property <{ parent: int, item: int }> selected-item;

    in property <length> window-height;

    forward-focus: i-group-list-view;

    i-group-list-view := GroupListView {
        selection-mode: Custom;
        model: BookmarksAdapter.bookmarks;

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                BookmarksAdapter.open-previous-dir();
                return accept;
            }

            if (event.text == " ") {
                root.selected-item = BookmarksAdapter.selected-item();

                if (root.selected-item.parent >= 0 && root.selected-item.item >= 0) {
                    root.open-item-context-menu(root.selected-item.parent, root.selected-item.item, { x: Space.medium, y: root.height / 2 })
                }

                return accept;
            }


            if (event.text == Key.DownArrow) {
                BookmarksAdapter.open-next-dir();
                return accept;
            }

            reject
        }

        item-pointer-event(par-index, index, event, position) => {
            root.focus();

            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.up) {
                BookmarksAdapter.open-dir(par-index, index);
                root.item-clicked();
            }

            if (event.button == PointerEventButton.right && event.kind == PointerEventKind.up) {
                open-item-context-menu(par-index, index, position);
            }
        }

        i-context-menu := ContextMenu {
            item-clicked(row) => {
                BookmarksAdapter.item-context-menu-action(root.item-context-menu-par-index,
                    root.item-context-menu-item-index, self.model[row].spec);
            }
            closed => {
                i-group-list-view.focus();
            }
        }
    }

    function open-item-context-menu(par-index: int, index: int, position: Point) {
        i-context-menu.model = BookmarksAdapter.get-item-context-menu(par-index, index);

        if (i-context-menu.model.length == 0) {
            return;
        }

        root.item-context-menu-item-index = index;
        root.item-context-menu-par-index = par-index;
        i-context-menu.x = position.x;

        // FIXME: remove this hacky workaround after there is a solution for slint winit PopupWindows
        i-context-menu.y = Size.large + position.y + i-context-menu.model.length * Size.small > root.window-height ?
            position.y + root.window-height - (Size.large + position.y + i-context-menu.model.length * Size.small) : position.y;

        if (i-group-list-view.has-focus) {
            i-context-menu.show-and-focus();
        } else {
            i-context-menu.show();
        }
    }
}