// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { AboutDialog } from "../dialogs/about-dialog.slint";

export global DialogAdapter {
    callback close-about();

    in property <bool> show-about;
}

export component DialogView {
    if (DialogAdapter.show-about) : Rectangle {
        preferred-width: 100%;
        preferred-height: 100%;
        background: #000000;
        opacity: 0.5;

        TouchArea {}
    }

    if (DialogAdapter.show-about) : AboutDialog {
        cancel-clicked => {
            DialogAdapter.close-about();
        }
    }
}