// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { Space, ScrollView, ExtraLargeTitle, Palette, Button, Icons, Icography, LargeLabel,
    ListViewItem, HeaderBar, RoundButton, ContextMenu, LoadingIndicator } from "../_imports/coop-widgets.slint";
import { Launcher, LauncherItem } from "../widgets/launcher.slint";

export global GamesAdapter {
    callback back();
    callback get-context-menu() -> [ListViewItem];
    callback context-menu-action(/* spec */ string);
    callback launch-game(/* row */ int);
    callback current-game-changed(/* current-game */ int);

    in property <[LauncherItem]> games;
    in property <[LauncherItem]> current-game-meta;
    in property <bool> loading;
    in property <string> title;
    in-out property <int> current-game;
}

export component GamesView {
    private property <[ListViewItem]> context-menu;
    private property <float> display-loading;

    VerticalLayout {
        HeaderBar {
            action-icon: Icons.arrow-back;
            action-enabled: true;
            title: GamesAdapter.title;

            i-menu-button := RoundButton {
                icon: Icons.more-vert;
                horizontal-stretch: 0;

                clicked => {
                    root.context-menu = GamesAdapter.get-context-menu();

                    if (root.context-menu.length == 0) {
                        return;
                    }

                    i-context-menu.show();
                }
            }

            action => {
                GamesAdapter.back();
            }

            i-context-menu := PopupWindow {
                x: i-menu-button.x - (128px - i-menu-button.width);
                y: i-menu-button.y + i-menu-button.height;

                ContextMenu {
                    min-width: 128px;
                    model: root.context-menu;

                    item-clicked(row) => {
                        GamesAdapter.context-menu-action(self.model[row].spec);
                    }
                }
            }
        }

        VerticalLayout {
            padding-left: Space.large;
            padding-right: Space.large;
            spacing: Space.large;

            i-launcher := Launcher {
                vertical-stretch: 0;
                model: GamesAdapter.games;
                current-item <=> GamesAdapter.current-game;

                launch(index) => {
                    GamesAdapter.launch-game(index);
                }

                current-item-changed(current-game) => {
                    GamesAdapter.current-game-changed(current-game);
                }
            }

            ScrollView {
                vertical-stretch: 1;

                Rectangle {
                    TouchArea {
                        clicked => {
                            i-launcher.focus();
                        }
                    }

                    VerticalLayout {
                        spacing: Space.large;
                        alignment: start;

                        ExtraLargeTitle {
                            text: GamesAdapter.games[GamesAdapter.current-game].text;
                            horizontal-alignment: left;
                        }

                        for item in GamesAdapter.current-game-meta : HorizontalLayout {
                            alignment: start;
                            spacing: Space.medium;

                            Image {
                                source: item.image;
                                colorize: Palette.primary;
                                width: Icography.small;
                            }

                            i-label := LargeLabel {
                                text: item.text;
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                color: Palette.foreground;
                                horizontal-stretch: 1;
                                overflow: elide;
                            }
                        }

                        HorizontalLayout {
                            alignment: start;
                            spacing: Space.medium;
                            padding-top: Space.medium;

                            Button {
                                text: @tr("Play");

                                clicked => {
                                    GamesAdapter.launch-game(GamesAdapter.current-game);
                                }
                            }

                            // Button {
                            //     icon: Icons.filled-settings;
                            // }
                        }
                    }
                }
            }
        }
    }

    if (root.display-loading >= 1.0) : LoadingIndicator {
        width: 100%;
        height: 100%;
    }

    states [
        loading when GamesAdapter.loading : {
            display-loading: 1.0;

            in {
                animate display-loading { duration: 500ms; }
            }
        }
    ]
}