// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { RoundButton, ContextMenu, LineEdit, ScrollView, Button, LoadingIndicator } from "@coop/widgets.slint";
import { HeaderBar } from "@coop/building-blocks.slint";
import { Palette, Icons, Space, Icography, Radius } from "@coop/styling.slint";
import { ListViewItem } from "@coop/structs.slint";
import { SmallTitle, ExtraLargeTitle, LargeLabel, FocusBorder } from "@coop/components.slint";
import { Launcher, LauncherItem } from "../widgets/launcher.slint";

export global GameSettingsAdapter {
    in property <string> title;
    in property <string> arguments;
    in property <int> row;

    callback set-arguments(/* row */ int, /* arguments */ string);
    callback close();
}

component GameSettingsView {
    in property <length> header-offest;

    Rectangle {
        background: Palette.background;

        VerticalLayout {
            HeaderBar {
                action-icon: Icons.arrow-back;
                action-enabled: true;
                title: "\{GameSettingsAdapter.title} (Settings)";
                offset: root.header-offest;

                i-menu-button := RoundButton {
                    icon: Icons.more-vert;
                    horizontal-stretch: 0;

                    clicked => {
                        i-context-menu.model = GamesAdapter.get-context-menu();

                        if (i-context-menu.model.length == 0) {
                            return;
                        }

                        i-context-menu.show();
                    }
                }

                action => {
                    GameSettingsAdapter.close();
                }

                i-context-menu := ContextMenu {
                    min-menu-width: 94px;
                    offset-x: -self.min-menu-width;
                    offset-y: i-menu-button.height;

                    item-clicked(row) => {
                        GamesAdapter.context-menu-action(self.model[row].spec);
                    }
                }
            }

            VerticalLayout {
                x: (parent.width - self.width) / 2;
                width: min(root.width, 640px);
                padding: Space.large;
                spacing: Space.medium;
                alignment: start;

                SmallTitle {
                    text: @tr("Arguments");
                }

                i-arguments := LineEdit {
                    placeholder-text: @tr("Insert command line arguments");
                    text: GameSettingsAdapter.arguments;

                    accepted => {
                        GameSettingsAdapter.set-arguments(GameSettingsAdapter.row, self.text);
                    }
                }
            }
        }
    }
}

export global GamesAdapter {
    callback back();
    callback get-context-menu() -> [ListViewItem];
    callback context-menu-action(/* spec */ string);
    callback get-item-context-menu() -> [ListViewItem];
    callback item-context-menu-action(/* index */ int, /* spec */ string);
    callback launch-game(/* index */ int);
    callback current-game-changed(/* current-game */ int);

    in property <[LauncherItem]> games;
    in property <[LauncherItem]> current-game-meta;
    in property <bool> loading;
    in property <string> title;
    in property <bool> display-settings;
    in-out property <int> current-game;
}

export component GamesView {
    private property <float> display-loading;
    private property <int> item-context-menu-item-row;

    in property <length> header-offest;

    forward-focus: i-launcher;

    VerticalLayout {
        padding-bottom: 1px;

        HeaderBar {
            action-icon: Icons.arrow-back;
            action-enabled: true;
            title: GamesAdapter.title;
            offset: root.header-offest;

            i-context-menu := ContextMenu {
                min-menu-width: 94px;
                offset-x: -((self.x + self.min-menu-width) - (i-menu-button.x + i-menu-button.width));
                offset-y: i-menu-button.height;

                item-clicked(row) => {
                    GamesAdapter.context-menu-action(self.model[row].spec);
                }
            }

            i-menu-button := RoundButton {
                icon: Icons.more-vert;
                horizontal-stretch: 0;

                clicked => {
                    i-context-menu.model = GamesAdapter.get-context-menu();

                    if (i-context-menu.model.length == 0) {
                        return;
                    }

                    if (i-launcher.has-focus) {
                        i-context-menu.show-and-focus();
                    } else {
                        i-context-menu.show();
                    }
                }
            }

            action => {
                GamesAdapter.back();
            }
        }

        i-background := Rectangle {
            x: 0;
            width: parent.width - 1px;
            border-radius: Radius.medium;
            clip: true;

            VerticalLayout {
                spacing: Space.medium;

                i-launcher := Launcher {
                    vertical-stretch: 0;
                    model: GamesAdapter.games;
                    current-item <=> GamesAdapter.current-game;

                    launch(index) => {
                        GamesAdapter.launch-game(index);
                    }

                    current-item-changed(current-game) => {
                        GamesAdapter.current-game-changed(current-game);
                    }

                    item-pointer-event(row, event, position) => {
                        if (event.button == PointerEventButton.right && event.kind == PointerEventKind.up) {
                            i-item-context-menu.model = GamesAdapter.get-item-context-menu();
                            if (i-item-context-menu.model.length == 0) {
                                return;
                            }

                            root.item-context-menu-item-row = row;
                            i-item-context-menu.x = position.x;
                            i-item-context-menu.y = position.y;

                            if (i-launcher.has-focus) {
                                i-item-context-menu.show-and-focus();
                            } else {
                                i-item-context-menu.show();
                            }
                        }
                    }

                    i-item-context-menu := ContextMenu {
                        item-clicked(row) => {
                            if (self.has-focus) {
                                i-launcher.focus();
                            }

                            GamesAdapter.item-context-menu-action(root.item-context-menu-item-row, self.model[row].spec);
                        }
                    }
                }

                ScrollView {
                    vertical-stretch: 1;

                    Rectangle {
                        TouchArea {
                            clicked => {
                                i-launcher.focus();
                            }
                        }

                        VerticalLayout {
                            padding-left: Space.large;
                            padding-right: Space.large;
                            spacing: Space.large;
                            alignment: start;

                            ExtraLargeTitle {
                                text: GamesAdapter.games[GamesAdapter.current-game].text;
                                horizontal-alignment: left;
                            }

                            for item in GamesAdapter.current-game-meta : HorizontalLayout {
                                alignment: start;
                                spacing: Space.medium;

                                Image {
                                    source: item.image;
                                    colorize: Palette.primary;
                                    width: Icography.small;
                                }

                                i-label := LargeLabel {
                                    text: item.text;
                                    vertical-alignment: center;
                                    horizontal-alignment: left;
                                    color: Palette.foreground;
                                    horizontal-stretch: 1;
                                    overflow: elide;
                                }
                            }

                            HorizontalLayout {
                                alignment: start;
                                spacing: Space.medium;

                                Button {
                                    text: @tr("Play");

                                    clicked => {
                                        GamesAdapter.launch-game(GamesAdapter.current-game);
                                    }
                                }

                                // Button {
                                //     icon: Icons.filled-settings;
                                // }
                            }
                        }
                    }
                }
            }

            if (i-launcher.has-focus) : FocusBorder {
                width: 100%;
                height: 100%;
                border-radius: i-background.border-radius;
            }
        }
    }

    if (GamesAdapter.display-settings) : GameSettingsView {
        width: 100%;
        height: 100%;
    }

    if (root.display-loading >= 1.0) : LoadingIndicator {
        width: 100%;
        height: 100%;
    }

    states [
        loading when GamesAdapter.loading : {
            display-loading: 1.0;

            in {
                animate display-loading { duration: 500ms; }
            }
        }
    ]
}