// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only


import { ListViewItem, HeaderBar } from "@coop/lib.slint";
import { Space, Palette, Typography, Icons } from "@coop/styling.slint";
import { HeaderBar, ControlBar } from "@coop/building-blocks.slint";
import { ScrollView, RoundButton, ContextMenu, TextEdit, LoadingIndicator } from "@coop/widgets.slint";

export global TextEditorAdapter {
    in property <string> title;
    in property <bool> loading;
    in property <bool> is-single-text;
    in property <bool> has-changes;
    in property <bool> read-only: true;
    in-out property <string> text;

    callback back();
    callback get-context-menu() -> [ListViewItem];
    callback context-menu-action(/* spec */ string);
    callback previous();
    callback next();
    callback update-text(/* text */ string) -> bool;
}

export component TextEditorView {
    in property <length> header-offest;

    private property <float> display-loading;
    private property <bool> text-loaded: TextEditorAdapter.text != "";

    states [
        loading when TextEditorAdapter.loading : {
            display-loading: 1.0;

            in {
                animate display-loading { duration: 500ms; }
            }
        }
    ]

    VerticalLayout {
        HeaderBar {
            action => {
                TextEditorAdapter.back();
            }

            action-icon: Icons.arrow-back;
            action-enabled: true;
            title: TextEditorAdapter.has-changes ? "\{TextEditorAdapter.title}*" : TextEditorAdapter.title;
            offset: root.header-offest;

            i-context-menu := ContextMenu {
                min-menu-width: 94px;
                offset-x: -((self.x + self.min-menu-width) - (i-menu-button.x + i-menu-button.width));
                offset-y: i-menu-button.height;

                item-clicked(row) => {
                    TextEditorAdapter.context-menu-action(self.model[row].spec);
                }
            }

            i-menu-button := RoundButton {
                clicked => {
                    i-context-menu.model = TextEditorAdapter.get-context-menu();

                    if (i-context-menu.model.length == 0) {
                        return;
                    }

                    i-context-menu.show();
                }

                icon: Icons.more-vert;
                horizontal-stretch: 0;
            }
        }

        HorizontalLayout {
            padding: Space.large;

            i-text-Edit := TextEdit {
                edited(text) => {
                    TextEditorAdapter.has-changes = TextEditorAdapter.update-text(text);
                }

                text <=> TextEditorAdapter.text;
                read-only: TextEditorAdapter.read-only;


            }
        }

        if (!TextEditorAdapter.is-single-text) : ControlBar {
            RoundButton {
                clicked => {
                    TextEditorAdapter.previous();
                }

                icon: Icons.arrow-back;
            }

            RoundButton {
                clicked => {
                    TextEditorAdapter.next();
                }

                icon: Icons.arrow-forward;
            }
        }
    }

    if (root.display-loading >= 1.0) : LoadingIndicator {
        width: 100%;
        height: 100%;
    }
}