// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../coop/theme.slint";
import { LargeTitle } from "../components/components.slint";
import { Spacer } from "../layouts/layouts.slint";

// `HeaderBar` is a bar with a title and a content area.
export component HeaderBar inherits HorizontalLayout {
    // Defines the title text of the header bar.
    in property <string> title: "title";

    spacing: Theme.spaces.medium;
    padding_left: Theme.spaces.large;
    padding_right: Theme.spaces.large;
    padding_top: Theme.spaces.small;
    padding_bottom: Theme.spaces.small;
    height: Theme.sizes.large;

    i_title := LargeTitle {  
        text: root.title;
        vertical-alignment: center;
        horizontal_alignment: left;
        horizontal_stretch: 1;
    }

    @children
}