// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { RoundButton } from "../widgets/button.slint";
import { MediumTitle } from "../components/label.slint";
import { Spacer } from "../layouts/spacer.slint";
import { Theme, Icons } from "../coop/theme.slint";
import { Icon } from "../components/icon.slint";

// `SideBar` is a bar with vertical arranged children.
export component SideBar {
    private property <bool> on_break_point: root.responsive && root.parent_width < root.break_point;

    // Describes the title of the sidebar.
    in property <string> title;

    // Defines the parent width as reference fot the break point.
    in property <length> parent_width;

    // If the `paren_width` is less then the break_point the layout of the side bar will switch.
    in property <length> break_point: 1100px;

    // If set to `true` the sidebar will draw over the content.
    in-out property <bool> expanded;

    // If set to `true` the layout flips by reaching the break point.
    in property <bool> responsive;

    width: root.on-break-point ? Theme.sizes.medium + 2 * Theme.spaces.medium : 160px;
    // background: Theme.brushes.background_alt;
    horizontal_stretch: 0;

    if (!root.expanded) : Rectangle {  
        y:0;  
        width: 100%;
        height: self.width;
        background: Theme.brushes.background_alt;

        i_open := RoundButton {
            x: Theme.spaces.medium;
            y: Theme.spaces.medium;
            visible: root.on_break_point;
            icon: Icons.fa_var_reorder;
            icon_background: Theme.brushes.background_alt;
            clicked => {  
                root.expanded = !root.expanded;
            }
        }
    }

    if (root.expanded && root.on_break_point) : Rectangle {
        x:0;
        width: root.parent-width;
        height: 100%;
        background: #00000040;

        TouchArea {
            clicked => { root.expanded = false; }
        }
    }

    i_content := Rectangle {
        x: 0px;
        width: 160px;
        background: Theme.brushes.background_alt;
        clip: true;

        VerticalLayout {  
            padding_top: Theme.spaces.medium;
            padding_bottom: Theme.spaces.medium;
            spacing: Theme.spaces.medium;
            alignment: start;
    
            if(root.on_break_point || root.title != "") : HorizontalLayout {  
                padding_left: Theme.spaces.medium;
                padding_right: Theme.spaces.medium;
                spacing: Theme.spaces.large;
                vertical_stretch: 0;
              
                if(root.on_break_point) : RoundButton {
                    icon: Icons.fa_var_reorder;
                    icon_background: Theme.brushes.background_alt;
                    clicked => {  
                        root.expanded = !root.expanded;
                    }
                }
    
                if(root.title != "") : MediumTitle {
                    text: root.title;
                    vertical_alignment: center;
                    horizontal_alignment: root.on_break_point ? left : center;
                }
            }
    
            @children

            Spacer {}
        }
    }
    
    states [
        expanded when root.expanded: {
            i_content.x: 0;

            in {
                animate i_content.x { duration: Theme.durations.fast; }
            }

            out {
                animate i_content.x { duration: Theme.durations.fast; }
            }
        in {
                animate i_content.x { duration: Theme.durations.fast; }
            }
        out {
                animate i_content.x { duration: Theme.durations.fast; }
            }
        }
        on_break_point when root.on_break_point: {
            i_content.x: - i_content.width;
        }
    ]
}

component SideBarTest inherits Rectangle {
    min_width: 900px;
    height: 400px;
    background: Theme.brushes.background;

    GridLayout {  
        Rectangle {  
            col: 1;
            min_width: 200px;
            horizontal_stretch: 1;

            Text {
                x:0;y:0;
                text: "content";
            }
        }

        i_side_bar := SideBar { 
            responsive: true;
            col: 0;
            height: 100%;
            title: "My App";

            parent_width: parent.width;
        }   
    }
}