# SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
# SPDX-License-Identifier: MIT

[package]
name = "platforms_support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
