// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: GPL-3.0-only

import { LineEdit, Button, Space, HorizontalBox } from "../_imports/coop_widgets.slint";
import { DialogBase } from "dialog-base.slint";

export component TextInputDialog inherits DialogBase {
    callback cancel-clicked <=> i-cancel-button.clicked;
    callback default-clicked <=> i-default-button.clicked;

    in-out property <string> text <=> i-line-edit.text;
    in property <string> default-button-text <=> i-default-button.text;

    i-line-edit := LineEdit {}

    HorizontalLayout {
        padding-top: Space.medium;
        spacing: Space.medium;
        alignment: end;

        i-cancel-button := Button {
            text: @tr("Cancel");
        }

        i-default-button := Button {
            text: "blub";
            primary: true;
        }
    }

    init => {
        i-line-edit.focus();
        i-line-edit.select-all();
    }
}