// SPDX-FileCopyrightText: 2023 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Duration } from "../styling.slint";

export component Carousel {
    in property <int> current-page;

    Rectangle {
        clip: true;
        width: 100%;
        height: 100%;

        i-layout := HorizontalLayout {
            x: -root.current-page * root.width;
            height: 100%;

            @children

            animate x { duration: Duration.slow; easing: cubic-bezier(0.05, 0.7, 0.1, 1.0); }
        }
    }
}