// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Duration, Icography, Radius, Palette, Icons, Size, Space, State } from "../styling.slint";
import { FocusBorder, Popup, LargeLabel } from "../components.slint";
import { ItemDelegate } from "../delegates.slint";
import { ListViewItem } from "../structs.slint";

export component ComboBox {
    private property <length> scroll-delta: 2px;

    callback selected(/* current-index */ int);

    in property <[ListViewItem]> model;
    in property <bool> enabled: true;
    in property <string> placeholder-text;
    out property <ListViewItem> current-value: root.current-index < 0 || root.current-index > root.model.length ? {} : root.model[root.current-index];
    out property <bool> has-focus: i-focus-scope.has-focus;
    in-out property <int> current-index: -1;

    accessible-role: combobox;
    accessible-value: root.current-index;
    min-width: max(Size.large, i-layout.min-width);
    min-height: max(Size.medium, i-layout.min-height);
    horizontal-stretch: 1;
    vertical-stretch: 0;

    i-background := Rectangle {
        property <brush> foreground: Palette.foreground;

        border-radius: Radius.small;
        background: Palette.surface;

        i-layout := HorizontalLayout {
            padding-left: Space.medium;
            padding-right: Space.medium;
            spacing: Space.small;

            if (root.current-index >= 0 && root.current-index < root.model.length) : LargeLabel {
                vertical-alignment: center;
                text: root.model[root.current-index].text;
                color: i-background.foreground;
                overflow: elide;
                horizontal-stretch: 1;
                horizontal-alignment: left;
            }

            // placeholder
            if (root.current-index < 0) : LargeLabel {
                text <=> root.placeholder-text;
                vertical-alignment: center;
                color: Palette.border;
                horizontal-stretch: 1;
                horizontal-alignment: left;
                overflow: elide;
            }

            i-icon := Image {
                y: (parent.height - self.height) / 2;
                colorize: i-background.foreground;
                width: Icography.large;
                source: Icons.arrow-drop-down;
            }
        }

        animate foreground, background { duration: Duration.fast; }
    }

    i-touch-area := TouchArea {
        enabled: root.enabled;

        clicked => { i-popup.show(); }

        // FIXME: wait for slint 1.3
        // scroll-event(event) => {
        //     if (event.delta-y < -root.scroll-delta) {
        //         root.move-selection-up();
        //         return accept;
        //     }

        //     if (event.delta-y > root.scroll-delta) {
        //         root.move-selection-down();
        //         return accept;
        //     }

        //     reject
        // }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0px; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.move-selection-up();
                return accept;
            }

            if (event.text == Key.DownArrow) {
                root.move-selection-down();
                return accept;
            }

            return reject;
        }
    }

    if (i-focus-scope.has-focus) : FocusBorder {
        width: root.width + 4px;
        height: root.height + 4px;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        border-radius: i-background.border-radius + 2px;
    }

    i-popup := Popup {
        x: 0;
        y: i-background.y + i-background.height + Space.small;
        width: i-background.width;

        HorizontalLayout {
            padding: 1px;

            VerticalLayout {
                padding: 4px;

                for item[index] in root.model : ItemDelegate {
                    text: item.text;
                    selected: index == root.current-index;

                    clicked => {
                        root.select(index);
                    }
                }
            }
        }
    }

    function select(index: int) {
        root.current-index = index;
        root.selected(root.current-index);
    }

    function move-selection-up() {
        root.select(Math.max(root.current-index - 1, 0));
    }

    function move-selection-down() {
        root.select(Math.min(root.current-index + 1, root.model.length - 1));
    }

    states [
        disabled when !root.enabled: {
            i-background.background: Palette.surface-disabled;
            i-background.foreground: Palette.foreground-disabled;
        }
        pressed when i-touch-area.pressed: {
            i-background.background:  Palette.surface.darker(State.pressed);
            i-icon.colorize: Palette.foreground.darker(State.pressed);
            i-background.foreground: Palette.foreground.darker(State.pressed);
        }
        hover when i-touch-area.has-hover: {
            i-background.background: Palette.surface.darker(State.hover);
            i-icon.colorize: Palette.foreground.darker(State.hover);
            i-background.foreground: Palette.foreground.darker(State.hover);
        }
    ]
}