// SPDX-FileCopyrightText: 2023 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT


import { Duration, Space, Palette } from "../styling.slint";

component LoadingStick inherits Rectangle {
    in property <bool> active;

    width: 4px;
    height: 64px;
    background: Palette.surface;
    border-radius: 2px;

    states [
        active when root.active : {
            root.background: Palette.accent;
        }
    ]
}

export component LoadingIndicator {
    private property <int> stick-count: 6;
    private property <float> active-stick: (root.stick-count + 1) * mod(animation-tick(), 1s) / 1s;

    min-width: i-layout.min-width;
    min-height: i-layout.min-height;

    Rectangle {
        background: #00000099;
    }

    TouchArea {}

    i-layout := VerticalLayout {
        alignment: center;

        HorizontalLayout {
            alignment: center;
            spacing: Space.medium;

            for i in root.stick-count : LoadingStick {
                active: i <= active-stick - 1;
                y: (parent.height - self.height) / 2;
            }
        }
    }
}