// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../coop/theme.slint";

// `ProgressBar` informs about current progress of ongoing process.
export component ProgressBar inherits Rectangle { 
    // Represents the current progress.
    //
    // Must be a progress between 0.0 and 1.0.
    in property <float> progress: 0.0;

    // If set to `true` the progress bar shows generic progress.
    in property <bool> indeterminate;

    min-width: Theme.sizes.large;
    height: Theme.sizes.extra_extra_small;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    background: Theme.brushes.surface;
    border_radius: Theme.radius.extra_extra_small;
    clip: true;

    i_track := Rectangle {
        x: !root.indeterminate ? 0px: parent.width * mod(animation-tick(), 2s) / 2s;
        y: (parent.height - self.height) / 2;
        width: !root.indeterminate ?  parent.width * root.progress: root.width / 2;
        height: 100%;
        background: Theme.brushes.primary;
        border_radius: root.border_radius;
    }
}

component ProgressBarExample inherits Rectangle {
    width: 600px;
    height: 400px;
    background: Theme.brushes.background;

    VerticalLayout {  
        padding: Theme.spaces.large;
        spacing: Theme.spaces.large;
        alignment: center;

        ProgressBar {  
            progress: 0.5;
        }

        ProgressBar {  
            indeterminate: true;
        }
    }
}