// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Duration, Palette, Size, State } from "../styling.slint";
import { ButtonBase } from "../base-widgets.slint";

export component RoundButton {
    callback clicked <=> i-base.clicked;

    in property <image> icon <=> i-base.icon;
    in property <string> text <=> i-base.text;
    out property <bool> has-focus: i-base.has-focus;
    out property <bool> pressed: self.enabled && i-base.pressed;
    in-out property <bool> enabled: true;
    in-out property <brush> icon-background: Palette.background;

    accessible-role: button;
    min-height: max(Size.medium, i-base.min-height);
    width: self.height;
    vertical-stretch: 0;
    horizontal-stretch: 0;

    i-base := ButtonBase {
        enabled: root.enabled;
        background: root.icon-background;
        text-color: Palette.foreground;
        icon-color: self.text-color;
        padding-left: 0px;
        padding-right: 0px;
        border-radius: max(self.width, self.height) / 2;

        animate text-color { duration: Duration.fast; }
    }

    states [
        disabled when !root.enabled: {
            i-base.text-color: Palette.foreground-disabled;
        }
        pressed when i-base.focus-pressed: {
            i-base.background: root.icon-background.darker(State.pressed);
            i-base.text-color: Palette.foreground.darker(State.pressed);
        }
        hover when i-base.has-hover: {
            i-base.background: root.icon-background.darker(State.hover);
            i-base.text-color: Palette.foreground.darker(State.hover);
        }
    ]

    animate icon-background { duration: Duration.fast; }
}