// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Duration, Icography, Radius, Palette, State, Space, Size, Icons } from "../styling.slint";
import { SelectionMode } from "../enums.slint";
import { ListView } from "list-view.slint";
import { LineEdit } from "line-edit.slint";
import { ListViewItem, TableRowItem } from "../structs.slint";
import { Spacer } from "../layouts/spacer.slint";
import { FocusBorder, LargeLabel } from "../components.slint";

component TableViewColumn inherits Rectangle {
    callback clicked <=> i-touch-area.clicked;
    callback adjust-size(/* size*/ length);

    in property <SortOrder> sort-order: SortOrder.unsorted;

    background: Palette.background;

    i-touch-area := TouchArea {
        width: parent.width - 11px;
    }

    HorizontalLayout {
        padding-left: Space.medium;
        padding-right: Space.medium;
        spacing: Space.small;

        HorizontalLayout {
            @children
        }

        i-icon := Image {
            image-fit: contain;
            colorize: Palette.foreground;
            visible: root.sort-order != SortOrder.unsorted;
            width: Icography.small;
            y: (parent.height - self.height) / 2;
            source: root.sort-order == SortOrder.ascending ? Icons.arrow-downward : Icons.arrow-upward;

            animate colorize { duration: Duration.fast; }
        }
    }

    // border
    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: Palette.border-disabled;
    }

    Rectangle {
        x: parent.width - 1px;
        width: 1px;

        i-movable-touch-area := TouchArea {
            width: 10px;
            mouse-cursor: ew-resize;

            moved => {
                if (self.pressed) {
                    adjust_size(self.mouse-x - self.pressed-x);
                }
            }
        }

        animate background { duration: Duration.fast; }

        states [
            hover when i-movable-touch-area.has-hover : {
                background: Palette.background.darker(State.hover);
            }
        ]
    }

    states [
        pressed when i-touch-area.pressed : {
            background: Palette.background.darker(State.pressed);
        }
        hover when i-touch-area.has-hover : {
            background: Palette.background.darker(State.hover);
        }
    ]
}

component TableViewCell inherits Rectangle {
    clip: true;
    min-height: Size.small;

    HorizontalLayout {
        padding-left: Space.medium;
        padding-right: Space.medium;
        spacing: Space.large;

        @children
    }
}

component TableViewRow inherits Rectangle {
    callback clicked <=> i-touch-area.clicked;
    callback pointer-event <=> i-touch-area.pointer-event;

    in property<bool> selected;
    in property <bool> alternative-background;
    out property<length> mouse-x <=> i-touch-area.mouse-x;
    out property<length> mouse-y <=> i-touch-area.mouse-y;

    min-width: i-layout.min-width;
    min-height: max(Size.small, i-layout.min-height);
    border-radius: 4px;
    background: root.alternative-background ? Palette.background-alt : transparent;

    i-touch-area := TouchArea {}

    i-layout := HorizontalLayout {
       @children
    }

    states [
        pressed when i-touch-area.pressed : {
            root.background: Palette.background.darker(State.pressed);
        }
        hover when i-touch-area.has-hover : {
            root.background: Palette.background.darker(State.hover);
        }
        selected when root.selected : {
            root.background: Palette.background.darker(State.selected);
        }
    ]
}

export component StandardTableView {
    private property <length> min-header-height: Size.small;
    private property <int> into-view-row;
    private property <length> row-height: i-list-view.viewport-height / rows.length;
    private property <length> into-view-row-y: i-list-view.viewport-y + into-view-row * row-height;

    callback sort-ascending(/* column-index */ int) -> bool;
    callback sort-descending(/* column-index */ int) -> bool;
    callback row-pointer-event(/* row-index */ int,  /* event */ PointerEvent, /* absolute mouse position */ Point);
    callback current-row-changed(/* current-row */ int);
    callback key-pressed(/* event */ KeyEvent) -> EventResult;
    callback item-accepted(/* row-index */ int, /* column-index */ int, /* text */ string);

    in property <[TableRowItem]> rows;
    in property <bool> zebra-pattern;
    in property <SelectionMode> selection-mode: SelectionMode.Single;
    in property <{ row: int, column: int}> edit-item: { row: -1, column: -1 };
    out property <int> current-sort-column: -1;
    out property <bool> has-focus: i-focus-scope.has-focus;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;

    min-width: 400px;
    min-height: 100px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    forward-focus: i-focus-scope;

    i-focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks

        key-pressed(event) => {
            if (root.key-pressed(event) == accept) {
                return accept;
            }

            if (root.selection-mode != SelectionMode.Custom) {
                if (event.text == Key.UpArrow) {
                    root.set-current-row(root.current-row - 1);
                    return accept;
                } else if (event.text == Key.DownArrow) {
                    root.set-current-row(root.current-row + 1);
                    return accept;
                }
            }

            reject
        }
    }

    i-background := Rectangle {
        border-radius: Radius.medium;

        VerticalLayout {
            spacing: Space.small;

            Rectangle {
                clip: true;
                vertical-stretch: 0;
                min-height: i-header-layout.min-height;

                i-header-layout := HorizontalLayout {
                    width: max(self.preferred-width, parent.width);
                    x: i-list-view.viewport-x;
                    min-height: root.min-header-height;

                    for column[index] in root.columns : TableViewColumn {
                        sort-order: column.sort-order;
                        horizontal-stretch: column.horizontal-stretch;
                        min-width: max(column.min-width, column.width);
                        preferred-width: self.min-width;
                        max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                        LargeLabel {
                            vertical-alignment: center;
                            text: column.title;
                            overflow: elide;
                        }

                        clicked => {
                            root.sort(index);
                        }

                        adjust-size(diff) => {
                            column.width = max(1px, self.width + diff);
                        }
                    }
                }
            }

            i-list-view := ListView {
                vertical-stretch: 1;

                for row[row-index] in root.rows : TableViewRow {
                    alternative-background: mod(row-index, 2) != 0 && root.zebra-pattern;
                    selected: (row-index == root.current-row && root.selection-mode == SelectionMode.Single)
                        || (row.selected && root.selection-mode == SelectionMode.Custom);

                    for cell[column-index] in row.model : TableViewCell {
                        private property <bool> edit: row-index == root.edit-item.row && column-index == root.edit-item.column;

                        horizontal-stretch: root.columns[column-index].horizontal-stretch;
                        min-width: max(columns[column-index].min-width, columns[column-index].width);
                        preferred-width: self.min-width;
                        max-width: (column-index < columns.length && columns[column-index].width >= 1px) ?
                            max(columns[column-index].min-width, columns[column-index].width) : 100000px;

                        if (cell.leading-icon.width > 0 && cell.leading-icon.height > 0) : Image {
                            source: cell.leading-icon;
                            width: Icography.small;
                            colorize: cell.highlighted ? Palette.primary : Palette.foreground;
                        }

                        if (!edit && cell.text != "") : LargeLabel {
                            text: cell.text;
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            horizontal-stretch: 1;
                            overflow: elide;
                        }

                        if (edit) : LineEdit {
                            y: (parent.height - self.height) / 2;
                            height: Size.extra-small;
                            text: cell.text;
                            horizontal-stretch: 1;

                            accepted(text) => {
                                root.item-accepted(row-index, column-index, text);
                            }
                        }

                        if (cell.trailing-icon.width > 0 && cell.trailing-icon.height > 0) : Image {
                            source: cell.trailing-icon;
                            colorize: Palette.foreground;
                            width: Icography.small;
                        }
                    }

                    clicked => {
                        root.set-current-row(row-index);
                    }

                    pointer-event(event) => {
                        root.row-pointer-event(row-index, event, {
                            x: self.absolute-position.x + self.mouse-x - root.absolute-position.x,
                            y: self.absolute-position.y + self.mouse-y - root.absolute-position.y,
                        });
                    }
                }
            }
        }

        @children
    }

    if (i-focus-scope.has-focus) : FocusBorder {
        width: 100%;
        height: 100%;
        border-radius: i-background.border-radius;
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }

        if(root.columns[index].sort-order == SortOrder.ascending) {
            if (root.sort-descending(index)) {
                root.columns[index].sort-order = SortOrder.descending;
            }
        } else {
            if (root.sort-ascending(index)) {
                root.columns[index].sort-order = SortOrder.ascending;
            }
        }

        root.current-sort-column = index;
    }

    public function set-current-row(index: int) {
        if (index < 0 || index >= root.rows.length || root.selection-mode == SelectionMode.None
            || root.selection-mode == SelectionMode.Custom) {
            return;
        }

        current-row = index;
        root.current-row-changed(current-row);

        bring-row-into-view(current-row);
    }

    public function bring-row-into-view(index: int) {
        into-view-row = index;

        if (into-view-row-y < 0) {
            i-list-view.viewport-y += 0 - into-view-row-y;
        }

        if (into-view-row-y + row-height > i-list-view.visible-height) {
            i-list-view.viewport-y -= into-view-row-y + row-height - i-list-view.visible-height;
        }
    }

    public function row-y(index: int) -> length {
        i-list-view.viewport-y + index * row-height + row-height / 2
    }
}