// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Duration, Icography, Radius, Palette, State, Space, Size, Icons } from "../styling.slint";
import { LargeLabel } from "../components/label.slint";
import { ListView } from "list-view.slint";
import { ListViewItem } from "../structs.slint";
import { Spacer } from "../layouts/spacer.slint";

component TableViewColumn inherits Rectangle {
    callback clicked <=> i-touch-area.clicked;
    callback adjust-size(/* size*/ length);

    in property <SortOrder> sort-order: SortOrder.unsorted;

    background: Palette.background;

    i-touch-area := TouchArea {
        width: parent.width - 11px;
    }

    HorizontalLayout {
        padding-left: Space.medium;
        padding-right: Space.medium;
        spacing: Space.small;

        HorizontalLayout {
            @children
        }

        i-icon := Image {
            image-fit: contain;
            colorize: Palette.foreground;
            visible: root.sort-order != SortOrder.unsorted;
            width: Icography.small;
            y: (parent.height - self.height) / 2;
            source: root.sort-order == SortOrder.ascending ? Icons.arrow-downward : Icons.arrow-upward;

            animate colorize { duration: Duration.fast; }
        }
    }

    // border
    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: Palette.border-disabled;
    }

    Rectangle {
        x: parent.width - 1px;
        width: 1px;

        i-movable-touch-area := TouchArea {
            width: 10px;
            mouse-cursor: ew-resize;

            moved => {
                if (self.pressed) {
                    adjust_size(self.mouse-x - self.pressed-x);
                }
            }
        }

        animate background { duration: Duration.fast; }

        states [
            hover when i-movable-touch-area.has-hover : {
                background: Palette.background.darker(State.hover);
            }
        ]
    }

    states [
        pressed when i-touch-area.pressed : {
            background: Palette.background.darker(State.pressed);
        }
        hover when i-touch-area.has-hover : {
            background: Palette.background.darker(State.hover);
        }
    ]
}

component TableViewCell inherits Rectangle {
    clip: true;

    HorizontalLayout {
        padding-left: Space.medium;
        padding-right: Space.medium;
        spacing: Space.large;

        @children
    }
}

component TableViewRow inherits Rectangle {
    callback clicked <=> i-touch-area.clicked;
    callback pointer-event <=> i-touch-area.pointer-event;

    in property<bool> selected;
    in property <bool> alternative-background;
    out property<length> mouse-x <=> i-touch-area.mouse-x;
    out property<length> mouse-y <=> i-touch-area.mouse-y;

    min-width: i-layout.min-width;
    min-height: max(Size.small, i-layout.min-height);
    border-radius: 4px;
    background: root.alternative-background ? Palette.background-alt : transparent;

    i-touch-area := TouchArea {}

    i-layout := HorizontalLayout {
       @children
    }

    states [
        pressed when i-touch-area.pressed : {
            root.background: Palette.background.darker(State.pressed);
        }
        hover when i-touch-area.has-hover : {
            root.background: Palette.background.darker(State.hover);
        }
        selected when root.selected : {
            root.background: Palette.background.darker(State.selected);
        }
    ]
}

export component StandardTableView {
    private property <length> min-header-height: Size.small;
    private property <length> item-height: i-list-view.viewport-height / rows.length;
    private property <length> current-item-y: i-list-view.viewport-y + current-row * item-height;

    callback sort-ascending(/* column-index */ int);
    callback sort-descending(/* column-index */ int);
    callback row-pointer-event(/* row-index */ int,  /* event */ PointerEvent, /* absolute mouse position */ Point);
    callback current-row-changed(/* current-row */ int);

    in property <[[ListViewItem]]> rows;
    in property <bool> zebra-pattern;
    out property <int> current-sort-column: -1;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    VerticalLayout {
        spacing: Space.small;

        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: i-header-layout.min-height;

            i-header-layout := HorizontalLayout {
                width: max(self.preferred-width, parent.width);
                x: i-list-view.viewport-x;
                min-height: root.min-header-height;

                for column[index] in root.columns : TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    LargeLabel {
                        vertical-alignment: center;
                        text: column.title;
                        overflow: elide;
                    }

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }
                }
            }
        }

        i-list-view := ListView {
            vertical-stretch: 1;

            for row[idx] in root.rows : TableViewRow {
                selected: idx == root.current-row;
                alternative-background: mod(idx, 2) != 0 && root.zebra-pattern;

                for cell[index] in row : TableViewCell {
                    private property <bool> has_inner_focus;

                    horizontal-stretch: root.columns[index].horizontal-stretch;
                    min-width: max(columns[index].min-width, columns[index].width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && columns[index].width >= 1px) ? max(columns[index].min-width, columns[index].width) : 100000px;

                    if (cell.leading-icon.width > 0 && cell.leading-icon.height > 0) : Image {
                        source: cell.leading-icon;
                        width: Icography.small;
                        colorize: cell.highlighted ? Palette.primary : Palette.foreground;
                    }

                    if (cell.text != "") : LargeLabel {
                        text: cell.text;
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        horizontal-stretch: 1;
                        overflow: elide;
                    }

                    if (cell.trailing-icon.width > 0 && cell.trailing-icon.height > 0) : Image {
                        source: cell.trailing-icon;
                        colorize: Palette.foreground;
                        width: Icography.small;
                    }
                }

                clicked => {
                    root.set-current-row(idx);
                }

                pointer-event(event) => {
                    root.row-pointer-event(idx, event, {
                        x: self.absolute-position.x + self.mouse-x - root.absolute-position.x,
                        y: self.absolute-position.y + self.mouse-y - root.absolute-position.y,
                    });
                }
            }
        }
    }

    FocusScope {
        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }
            reject
        }
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }

        if(root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    public function set-current-row(index: int) {
        if (index < 0 || index >= rows.length) {
            return;
        }

        current-row = index;
        root.current-row-changed(current-row);

        if (current-item-y < 0) {
            i-list-view.viewport-y += 0 - current-item-y;
        }

        if (current-item-y + item-height > i-list-view.visible-height) {
            i-list-view.viewport-y -= current-item-y + item-height - i-list-view.visible-height;
        }
    }
}