// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "_imports/coop_widgets.slint";
import { ColorPicker } from "color_picker.slint";
import { SpriteSetter } from "sprite_setter.slint";

export component SpriteEditor {
    private property <int> selected_color_index <=> i_color_picker.selected_color_index;
    in property <[color]> palette <=> i_color_picker.palette;
    in property <[int]> selected_sprite_colors <=> i_sprite_setter.colors;
    in property <length> sprite_width <=> i_sprite_setter.sprite_width;
    in property <length> sprite_height <=> i_sprite_setter.sprite_height;
    
    VerticalLayout {  
        padding: Theme.spaces.medium;

        HorizontalLayout {  
            spacing: Theme.spaces.large;

            i_sprite_setter := SpriteSetter {  
                selected_color_index: root.selected_color_index;
                palette: root.palette;
            }

            i_color_picker := ColorPicker {}
        }
    }
}

component SpriteEditorExample inherits Rectangle {
    property <color> c_green: green;
    property <color> c_red: red;
    property <color> c_transparent: transparent;

    width: 160px;
    height: 144px;
    background: Theme.brushes.background;

    SpriteEditor {  
        sprite_width: 2px;
        selected_sprite_colors: [
            0, 0, 0, 0
        ];
        palette: [
            c_transparent, c_green, c_red
        ];
    }
}