// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "_imports/coop_widgets.slint";
import { ColorButton } from "color_button.slint";

export component SpriteSetter {
    private property <length> offset: i_container.border_width + 1px;
    private property <length> pixel_width: 1px * (i_container.width - 2 * offset) / sprite_width; 
    private property <length> pixel_height: 1px * (i_container.height - 2 * offset) / sprite_height; 

    in property <length> sprite_width: 16px;
    in property <length> sprite_height: sprite_width;
    in-out property <[int]> colors;
    in property <[color]> palette;
    in property <int> selected_color_index;

    min_width: sprite_width;
    height: root.width;

    i_container := Rectangle {        
        border_width: 2px;
        border_color: Theme.brushes.border;

        for color_id[index] in colors : ColorButton {
            x: offset + self.width * mod(index, sprite_width / 1px);
            y: offset + self.height * floor(index * 1px / sprite_height);
            width: pixel_width;
            height: pixel_height;
            color: color_id <= palette.length ? palette[color_id] : transparent;

            clicked => {  
                root.colors[index] = root.selected_color_index;
            }
        }
    }
}

component SpriteSetterExample inherits Rectangle {
    property <color> default: green;
    property <color> set_color: red;

    width: 64px;
    height: 64px;

    SpriteSetter {  
        width: 100px;

        sprite_width: 2px;
        selected_color_index: 0;

        palette: [default, set_color];
        colors: [ 1, 1, 1 , 1];     
    }
}