// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow, KeyboardPage, KeyboardAdapter, GroupItemModel, coop } from "_imports/coop_widgets.slint";
import { BasicsPage, TypoPage, BrushesPage, ListPage } from "pages/pages.slint";
import { AppManager } from "app_manager.slint"; 
import { SideBarView } from "side_bar_view.slint";

export { KeyboardAdapter, coop }
export { AppManager }

export App := CoopWindow {
    min-width: 1000px;
    title: "Widgets gallery";

    Rectangle {
        background: coop.theme.brushes.background;
    }

    keyboard_page := KeyboardPage {
        keyboard_closed(key, text) => {
            AppManager.update_text(key, text);
        } 

        HorizontalLayout {   
            i_side_bar := SideBarView {
                property <GroupItemModel> widgets: {
                    text: "Widgets",
                    items: [
                        { text: "Basics" },
                        { text: "Lists" },
                    ]
                };

                property <GroupItemModel> resources: {
                    text: "Resources",
                    items: [
                        { text: "Brushes" },
                        { text: "Typography" },
                    ]
                };
  
                navigation_items: [widgets, resources];
            }
        
            if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 0) : BasicsPage {
                open_keyboard(key, text, placeholder, icon) => { keyboard_page.open-keyboard(key, text, placeholder, icon); }
            }
            if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 1) : ListPage {}
            if(i_side_bar.current_item.parent == 1 &&  i_side_bar.current_item.item == 0) : BrushesPage {}
            if(i_side_bar.current_item.parent == 1 &&  i_side_bar.current_item.item == 1) : TypoPage {}
        }
    }
}  