// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { CoopWindow, KeyboardPage, KeyboardAdapter, GroupItemModel, Theme, Icons } from "_imports/coop_widgets.slint";
import { BasicsPage, TypoPage, BrushesPage, ListPage, BookFlipPage } from "pages/pages.slint";
import { AppManager } from "app_manager.slint"; 
import { SideBarView } from "side_bar_view.slint";

export { KeyboardAdapter, Theme }
export { AppManager } 

export component App inherits CoopWindow {
    min_width: 800px;
    title: "Widgets gallery";

    Rectangle {
        background: Theme.brushes.background;
    }

    keyboard_page := KeyboardPage {
        keyboard_closed(key, text) => {
            AppManager.update_text(key, text);
        } 

        GridLayout {   
            Rectangle {  
                col: 1;

                if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 0) : BasicsPage {
                    open_keyboard(key, text, placeholder, icon) => { keyboard_page.open_keyboard(key, text, placeholder, icon); }
                } 
                if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 1) : ListPage {}
                if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 2) : BookFlipPage {}
                if(i_side_bar.current_item.parent == 1 &&  i_side_bar.current_item.item == 0) : BrushesPage {}
                if(i_side_bar.current_item.parent == 1 &&  i_side_bar.current_item.item == 1) : TypoPage {}
            }
            i_side_bar := SideBarView {
                col: 0;
                parent_width: root.width;
                title: "Gallery";
                responsive: true;

                property <GroupItemModel> widgets: {
                    text: "Widgets",
                    items: [
                        { leading_icon: Icons.fa_var_tachometer, text: "Basics" },
                        { leading_icon: Icons.fa_var_list, text: "Lists" },
                        { leading_icon: Icons.fa_var_book, text: "Book flip" },
                    ]
                };

                property <GroupItemModel> resources: {
                    text: "Resources",
                    items: [
                        { leading_icon: Icons.fa_var_paint_brush, text: "Brushes" },
                        { leading_icon: Icons.fa_var_pencil, text: "Typography" },
                    ]
                };
  
                navigation_items: [self.widgets, self.resources];
            }
        }
    }
}  