import { CoWindow, KeyboardPage, KeyboardAdapter, ParentItemModel, co } from "_imports/co_widgets.slint";
import { BasicsPage, TypoPage } from "pages/pages.slint";
import { settings, Test } from "settings.slint"; 
import { AppSideBar } from "app_side_bar.slint";

export { KeyboardAdapter, co }
export { settings }

export App := CoWindow {
    preferred-width: 900px;
    title: "Widgets gallery";

    Rectangle {  
        background: co.brushes.background;
    }

    KeyboardPage {
        keyboard_open <=> settings.keyboard_open;
        HorizontalLayout {   
            i_side_bar := AppSideBar {
                property <ParentItemModel> widgets: {
                    text: "Widgets",
                    items: [
                        { leading_icon: "", text: "Basics", trailing_icon: ""},
                    ]
                };

                property <ParentItemModel> resources: {
                    text: "Resources",
                    items: [
                        // { leading_icon: "", text: "Brushes", trailing_icon: ""},
                        { leading_icon: "", text: "Typography", trailing_icon: ""},
                    ]
                };

              
                navigation_items: [widgets, resources];
            }
        
            if(i_side_bar.current_item.parent == 0 &&  i_side_bar.current_item.item == 0) : BasicsPage {}
            if(i_side_bar.current_item.parent == 1 &&  i_side_bar.current_item.item == 0) : TypoPage {}
        }
    }
   
}  

