// SPDX-FileCopyrightText: 2022 Florian Blasius <flovanpt@posteo.de>
// SPDX-License-Identifier: MIT

import { SideBar, List, ParentItemModel } from "_imports/co_widgets.slint";

export AppSideBar := SideBar {
    property <[ParentItemModel]> navigation_items <=> i_navigation.model;
    property <{ parent: int, item: int }> current_item <=> i_navigation.current_item;

    width: 200px;
    height: 100%;

    i_navigation := List {}
}