// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "_imports/coop_widgets.slint";

export global AppManager  {
    callback open_keyboard(string, string, string, string);
    callback update_text(string, string);

    in-out property <bool> keyboard_enabled: false;
    in-out property <bool> widgets_enabled: true;
    in-out property <string> text_line_one;
    in-out property <string> text_line_two: "hello";
    in-out property <string> text_line_three: "hello";

    update_text(key, text) => {  
        if (key == "text_line_one") {
            root.text_line_one = text;
        }

        if (key == "text_line_two") {
            root.text_line_two = text;
        }

        if (key == "text_line_three") {
            root.text_line_three = text;
        }
    }
}