// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SideBar, List, GroupItemModel } from "_imports/coop_widgets.slint";

export component SideBarView inherits SideBar {
    in-out property <[GroupItemModel]> navigation_items <=> i_navigation.model;
    in-out property <{ parent: int, item: int }> current_item <=> i_navigation.current_item;

    i_navigation := List {
        vertical-stretch: 1;
        current-item-changed => { 
            root.expanded = false;
         }
    }
}