// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { SideBar, List, GroupItemModel } from "_imports/coop_widgets.slint";

export SideBarView := SideBar {
    property <[GroupItemModel]> navigation_items <=> i_navigation.model;
    property <{ parent: int, item: int }> current_item <=> i_navigation.current_item;

    i_navigation := List {
        vertical-stretch: 1;

        current_item_changed => {  
            root.expanded = false;
        }
    }
}