// SPDX-FileCopyrightText: 2022 Florian Blasius <co-sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { FocusBorder } from "../components/focus-border.slint";

export component FocusTouchArea inherits TouchArea {
    in property <length> focus-border-radius: 0px;
    out property <bool> focus-pressed: root.pressed || root.enter-pressed;
    out property <bool> has-focus <=> i-focus-scope.has-focus;

    private property <bool> enter-pressed;

    forward-focus: i-focus-scope;

    i-focus-scope := FocusScope {
        x:0;
        width: 0px; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if((event.text == " " || event.text == "\n") && !root.enter-pressed) {
                root.enter-pressed = true;
                root.clicked();
                return accept;
            }
            return reject;
        }

        key-released(event) => {
            if((event.text == " " || event.text == "\n") && root.enter-pressed) {
                root.enter-pressed = false;
                return accept;
            }
            return reject;
        }
    }

    if (i-focus-scope.has-focus) : FocusBorder {
        width: root.width + 4px;
        height: root.height + 4px;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        border-radius: root.focus-border-radius + 2px;
    }
}