// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

// workaround to get font displayed embedded on the softwarerendrer
// import "../assets/fonts/Roboto-Regular.ttf"; 
// import "../assets/fonts/Roboto-Medium.ttf"; 

import { Font } from "../co/typo.slint";
import { co } from "../co/co.slint";

// Base for labels. Set font settings by font property.
export BaseLabel := Text {
    // Defines the font settings.
    property <Font> font;

    color: co.theme.brushes.foreground;
    // font_family: font.family;
    font_size: font.size;
    font_weight: font.weight;
}

// Label with settings `co.theme.typo.label_small`.
export LabelSmall := BaseLabel {
    font: co.theme.typo.label_small;
}

// Label with settings `co.theme.typo.label_medium`.
export LabelMedium := BaseLabel {
    font: co.theme.typo.label_medium;
}

// Label with settings `co.theme.typo.label_large.
export LabelLarge := BaseLabel {
    font: co.theme.typo.label_large; 
}

// Title with settings `co.theme.typo.title_small`.
export TitleSmall := BaseLabel {
    font: co.theme.typo.title_small;
}

// Title with settings `co.theme.typo.title_medium`.
export TitleMedium := BaseLabel {
    font: co.theme.typo.title_medium;
}

// Title with settings `co.theme.typo.title_large.
export TitleLarge := BaseLabel {
    font: co.theme.typo.title_large;
}