import { co } from "../co/co.slint";

import { Keyboard } from "keyboard_widget.slint";

export KeyboardPage := Rectangle {
    property<bool> keyboard_open: false;

    container := Rectangle {
        width: 100%;
        height: 100%;
        @children
    }

    Keyboard {
        y: container.y + container.height;
        background: co.brushes.surface;

        TouchArea {  
            width: 100%;
            height: 100%;

            clicked => {  keyboard_open = false; }
        }
    }

    states [
        keyboard_open when root.keyboard_open : {
            container.y: -root.height;
        }
    ]

    transitions [  
        in keyboard_open : {
            animate container.y { duration: co.durations.fast; }
        }
        out keyboard_open : {
            animate container.y { duration:  co.durations.medium; }
        }
    ]
}