// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../coop/theme.slint";

import { Keyboard } from "keyboard_widget.slint";

// `KeyboardPage` can switch between its children an a `Keyboard`.
export component KeyboardPage {
    private property <bool> keyboard_open: false;

    // Called after keyboard is closed.
    callback keyboard_closed(string, string);

    preferred-width: 100%;
    preferred-height: 100%;

    i_container := Rectangle {
        @children
    }

    i_keyboard := Keyboard {
        y: i_container.y + i_container.height;

        close(key, text) => {
            root.keyboard_open = false;
            root.keyboard_closed(key, self.text);
         }
    }

    states [
        keyboard_open when root.keyboard_open: {
            i_container.y: -root.height;
        in {
            animate i_container.y { duration: Theme.durations.fast; }
        }
        out {
            animate i_container.y { duration:  Theme.durations.medium; }
        }
        }
    ]

    public function open_keyboard(key: string, text: string, placeholder: string, icon: string) {
        root.keyboard_open = true;
        i_keyboard.open(key, text, placeholder, icon);
    }
}